// Generated by wiz from omega.
// Every operation the document declares. Edit the document, not this file.

import type { Ack, LiveState, MarkdownRequest, ModelOption, OpenSessionRequest, PlanActionRequest, PlanDocument, PlanEditRequest, PlanModeRequest, PromptRequest, RenderedMarkdown, SelectModelRequest, Transcript, Workspace } from "./model.ts";
import { decodeAck, decodeLiveState, decodePlanDocument, decodeRenderedMarkdown, decodeTranscript, encodeMarkdownRequest, encodeOpenSessionRequest, encodePlanActionRequest, encodePlanEditRequest, encodePlanModeRequest, encodePromptRequest, encodeSelectModelRequest } from "./codec.ts";

/** One outgoing call, as built by a method and seen by every interceptor. */
export interface Call {
  method: string;
  url: string;
  headers: Record<string, string>;
  /** JSON text for an HTTP call, a framed protobuf message for a gRPC one. */
  body?: string | Uint8Array;
  /** Signal for cancellation or local timeout. */
  signal?: AbortSignal;
}

/** A call and what came back, before the status is judged. */
export interface CallResult {
  call: Call;
  response: Response;
}

/**
 * Per-call cancellation and deadline, the same two things a gRPC call takes.
 * There is deliberately no `headers` here: an HTTP document declares its
 * headers, so they are slots on the method rather than ambient metadata.
 */
export interface HttpCallOptions {
  /** Cancels the call. Whatever `fetch` does with an aborted signal happens. */
  signal?: AbortSignal;
  /**
   * A deadline for this call, enforced locally: the call aborts with a
   * `TimeoutError` when it passes, whatever the server is doing.
   */
  timeoutMs?: number;
}

/**
 * The caller's signal and the deadline as one signal, built per attempt so an
 * interceptor that calls `next` again gets a fresh deadline rather than one
 * that has already fired.
 */
function effectiveSignal(
  signal: AbortSignal | undefined,
  timeoutMs: number | undefined
): AbortSignal | undefined {
  const deadline =
    timeoutMs === undefined ? [] : [AbortSignal.timeout(timeoutMs)];
  return signal ? AbortSignal.any([signal, ...deadline]) : deadline[0];
}


/**
 * A wrapper around one call.
 *
 * One shape serves both protocols, so an interceptor can do the same four
 * things either side: change the call on the way in, change what comes back on
 * the way out, call `next` more than once to retry, or never call it and
 * answer from somewhere else. The call type is shared too, so an interceptor
 * that only touches the request - the common case, a token - is one generic
 * function that both sides accept.
 */
export type Interceptor<TResult> = (
  call: Call,
  next: (call: Call) => TResult
) => TResult;

/** Wraps an HTTP call. The response is raw: its status is judged afterwards. */
export type HttpInterceptor = Interceptor<Promise<CallResult>>;

/**
 * A chain per protocol, because what an interceptor gets back differs. Only the
 * protocols this document speaks are here, so an array can never be written
 * into a key nothing will read.
 */
export interface Interceptors {
  /** Outermost first: `[a, b]` runs a around b around the request. */
  http?: HttpInterceptor[];
}

/** Folds the chain right to left, so the first interceptor is the outermost. */
function chain<TResult>(
  interceptors: ReadonlyArray<Interceptor<TResult>> | undefined,
  invoke: (call: Call) => TResult
): (call: Call) => TResult {
  if (!interceptors || interceptors.length === 0) return invoke;
  return interceptors.reduceRight<(call: Call) => TResult>(
    (next, interceptor) => (call) => interceptor(call, next),
    invoke
  );
}

/**
 * The part of `fetch` this client calls, so a stub does not have to be a whole
 * one. A real `fetch` is assignable to it: it accepts wider input than this.
 */
export type FetchLike = (
  url: string,
  init: {
    method: string;
    headers: Record<string, string>;
    body?: string | Uint8Array;
    signal?: AbortSignal;
  }
) => Promise<Response>;


/**
 * An HTTP transport that executes an outgoing call.
 *
 * Symmetrical to `GrpcTransport`: a custom transport receives the `Call` and
 * returns a `Response`.
 */
export interface HttpTransport {
  call(call: Call): Promise<Response>;
}

function httpTransport(config: ClientConfig): HttpTransport {
  if (config.transport) {
    if (typeof config.transport === "function") {
      const fn = config.transport;
      return {
        call: (c) =>
          fn(c.url, {
            method: c.method,
            headers: c.headers,
            body: c.body,
            signal: c.signal,
          }),
      };
    }
    if (
      typeof config.transport === "object" &&
      "call" in config.transport &&
      !("duplex" in config.transport)
    ) {
      return config.transport;
    }
  }
  return {
    call: (c) =>
      globalThis.fetch(c.url, {
        method: c.method,
        headers: c.headers,
        body: c.body as BodyInit | undefined,
        signal: c.signal,
      }),
  };
}

export interface ClientConfig {
  /**
   * Prefix for every path. The document does not carry it: OpenAPI `servers`
   * describe environments, which is a runtime fact, not a compile-time one.
   */
  baseUrl: string;
  /**
   * Custom HTTP transport. Defaults to globalThis.fetch when omitted.
   */
  transport?: HttpTransport | FetchLike;
  /**
   * Wrappers around every call, outermost first. This is where an
   * Authorization header comes from, and where a retry or a log belongs.
   */
  interceptors?: Interceptors;
  /**
   * A deadline for every call, unless the call overrides it. Sent as
   * `grpc-timeout` where the protocol has one, and always enforced locally.
   */
  timeoutMs?: number;
}

const DEFAULTS: ClientConfig = {
  baseUrl: "",
};

/** A response outside 2xx. The parsed body is kept: that is where APIs explain. */
export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;
  readonly response: Response;

  constructor(status: number, body: unknown, response: Response) {
    super(`HTTP ${status} for ${response.url}`);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
    this.response = response;
  }
}

function encodePath(value: string | number | boolean): string {
  return encodeURIComponent(String(value));
}

function queryString(query: Record<string, unknown> | undefined): string {
  if (!query) return "";
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    // A repeated key is how every OpenAPI serialisation style spells an array.
    if (Array.isArray(value)) {
      for (const item of value) search.append(key, String(item));
      continue;
    }
    search.append(key, String(value));
  }
  const text = search.toString();
  return text ? `?${text}` : "";
}

function headerRecord(
  headers: Record<string, unknown> | undefined,
  cookie: Record<string, unknown> | undefined,
  contentType: string | undefined
): Record<string, string> {
  const record: Record<string, string> = {};
  if (contentType) record["content-type"] = contentType;

  for (const [key, value] of Object.entries(headers ?? {})) {
    if (value === undefined || value === null) continue;
    record[key] = String(value);
  }

  // Cookie parameters travel in one header, which is the only way HTTP has.
  const crumbs = Object.entries(cookie ?? {}).filter(
    ([, value]) => value !== undefined && value !== null
  );
  if (crumbs.length > 0) {
    record["cookie"] = crumbs
      .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
      .join("; ");
  }

  return record;
}

async function parseBody(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const text = await response.text();
  if (text === "") return undefined;
  const ct = (response.headers.get("content-type") ?? "").toLowerCase();
  const bun = (globalThis as any).Bun;
  if (ct.includes("jsonl") || ct.includes("json-lines") || ct.includes("x-jsonlines")) {
    try {
      return (bun?.JSONL ?? { parse: (t: string) => t.trim().split("\n").map((l: string) => JSON.parse(l)) }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("jsonc")) {
    try {
      return (bun?.JSONC ?? JSON).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("json5")) {
    try {
      return (bun?.JSON5 ?? JSON).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("yaml")) {
    try {
      return (bun?.YAML ?? { parse: (t: string) => JSON.parse(t) }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("xml")) {
    try {
      return (bun?.XML ?? { parse: (t: string) => t }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("erlang-binary") || ct.includes("etf")) {
    try {
      const bytes = new Uint8Array(await response.arrayBuffer());
      return typeof (globalThis as any).decodeErlangBinary === "function" ? (globalThis as any).decodeErlangBinary(bytes) : bytes;
    } catch {
      return text;
    }
  }
  if (ct.includes("erlang")) {
    try {
      return typeof (globalThis as any).decodeErlangText === "function" ? (globalThis as any).decodeErlangText(text) : text;
    } catch {
      return text;
    }
  }
  if (ct.includes("json")) {
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
  return text;
}

async function send(
  config: ClientConfig,
  call: Call,
  options: HttpCallOptions | undefined
): Promise<unknown> {
  const http = httpTransport(config);

  // The signal is built inside the attempt, not once per call, so an
  // interceptor that calls `next` again gets a fresh deadline rather than one
  // that has already fired. The caller's own signal spans every attempt.
  const invoke = async (outgoing: Call): Promise<CallResult> => {
    const activeCall: Call = {
      ...outgoing,
      signal: effectiveSignal(
        options?.signal,
        options?.timeoutMs ?? config.timeoutMs
      ),
    };
    return {
      call: activeCall,
      response: await http.call(activeCall),
    };
  };
  // The status is judged after the chain, so an interceptor sees the response
  // that a retry or a token refresh has to look at, not an exception.
  const settled = await chain(config.interceptors?.http, invoke)(call);

  const body = await parseBody(settled.response);
  if (!settled.response.ok) {
    throw new ApiError(settled.response.status, body, settled.response);
  }
  return body;
}

/**
 * Every operation the document declares.
 *
 * A caller that talks to one deployment can ignore this and use the
 * module-level functions below; a caller that talks to several holds one
 * client per configuration.
 */
export interface Client {
  /**
   * List workspaces and their sessions
   * 
   * Every directory with sessions on disk, each with its sessions nested.
   */
  listWorkspaces(callOptions?: HttpCallOptions): Promise<Workspace[]>;
  /**
   * List available models
   * 
   * Models the local omp install is authenticated for.
   */
  listModels(callOptions?: HttpCallOptions): Promise<ModelOption[]>;
  /**
   * Open or create a live session
   * 
   * Load a session as a live agent, or start a new one in `cwd`.
   * 
   * Idempotent for an already-loaded session: the existing live agent is
   * returned rather than a second one being created for the same file.
   */
  openSession(options: { body: OpenSessionRequest }, callOptions?: HttpCallOptions): Promise<LiveState>;
  /**
   * Read live session state
   * 
   * Current model, thinking level, streaming status and plan state.
   */
  getState(options: { path: { key: string } }, callOptions?: HttpCallOptions): Promise<LiveState>;
  /**
   * Read the session transcript
   * 
   * The session transcript, flattened into renderable parts.
   */
  getTranscript(options: { path: { key: string } }, callOptions?: HttpCallOptions): Promise<Transcript>;
  /**
   * Prompt the agent
   * 
   * Send a message. Returns as soon as the turn is scheduled; the reply
   * arrives as AG-UI frames on the session's WebSocket.
   */
  prompt(options: { path: { key: string }; body: PromptRequest }, callOptions?: HttpCallOptions): Promise<Ack>;
  /**
   * Abort the current turn
   * 
   * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
   */
  abort(options: { path: { key: string } }, callOptions?: HttpCallOptions): Promise<Ack>;
  /**
   * Select a model
   * 
   * Switch the live session's model, and optionally its thinking level.
   */
  selectModel(options: { path: { key: string }; body: SelectModelRequest }, callOptions?: HttpCallOptions): Promise<LiveState>;
  /**
   * Read the plan document
   * 
   * The plan document, its headings and the executable role tiers — the three
   * planning panes in one payload.
   */
  getPlan(options: { path: { key: string } }, callOptions?: HttpCallOptions): Promise<PlanDocument>;
  /**
   * Toggle plan mode
   * 
   * Turn plan mode on or off for the live session.
   */
  setPlanMode(options: { path: { key: string }; body: PlanModeRequest }, callOptions?: HttpCallOptions): Promise<PlanDocument>;
  /**
   * Edit the plan document
   * 
   * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
   */
  editPlan(options: { path: { key: string }; body: PlanEditRequest }, callOptions?: HttpCallOptions): Promise<PlanDocument>;
  /**
   * Resolve the plan review
   * 
   * Resolve the plan review: approve and execute, approve and compact,
   * approve into a fresh session, or refine with feedback.
   */
  resolvePlan(options: { path: { key: string }; body: PlanActionRequest }, callOptions?: HttpCallOptions): Promise<Ack>;
  /**
   * Render markdown to HTML
   * 
   * Render markdown with `Bun.markdown.html`.
   * 
   * The browser has no `Bun.markdown`, so every rendering in the UI —
   * transcript text, thinking blocks, the plan document — comes from here.
   */
  renderMarkdown(options: { body: MarkdownRequest }, callOptions?: HttpCallOptions): Promise<RenderedMarkdown>;
}

/**
 * A client bound to its own configuration.
 *
 * Two tenants, two base URLs or two credentials are two clients; nothing is
 * shared between them, and the module-level default is just one more.
 */
export function createClient(overrides: Partial<ClientConfig> = {}): Client {
  const config: ClientConfig = { ...DEFAULTS, ...overrides };

  return {
    async listWorkspaces(callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/workspaces`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as Workspace[];
    },
    async listModels(callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/models`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as ModelOption[];
    },
    async openSession(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeOpenSessionRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async getState(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/state`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as LiveState;
    },
    async getTranscript(options, callOptions) {
      return decodeTranscript(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/transcript`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Transcript;
    },
    async prompt(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/prompt`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePromptRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async abort(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/abort`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Ack;
    },
    async selectModel(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/model`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeSelectModelRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async getPlan(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as PlanDocument;
    },
    async setPlanMode(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/mode`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanModeRequest(options.body),
      }, callOptions) as string) as PlanDocument;
    },
    async editPlan(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "PUT",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/document`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanEditRequest(options.body),
      }, callOptions) as string) as PlanDocument;
    },
    async resolvePlan(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/action`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanActionRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async renderMarkdown(options, callOptions) {
      return decodeRenderedMarkdown(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/markdown`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeMarkdownRequest(options.body),
      }, callOptions) as string) as RenderedMarkdown;
    },
  };
}

let defaults: ClientConfig = { ...DEFAULTS };
let client: Client = createClient();

/**
 * Merges into the configuration the module-level functions use, so a base
 * URL and an interceptor can be set from different places.
 */
export function configure(next: Partial<ClientConfig>): void {
  defaults = { ...defaults, ...next };
  client = createClient(defaults);
}

export function currentConfig(): ClientConfig {
  return defaults;
}

/** The client `configure()` maintains, which hooks and other consumers default to. */
export function defaultClient(): Client {
  return client;
}

/**
 * List workspaces and their sessions
 * 
 * Every directory with sessions on disk, each with its sessions nested.
 */
export const listWorkspaces: Client["listWorkspaces"] = (callOptions) => client.listWorkspaces(callOptions);

/**
 * List available models
 * 
 * Models the local omp install is authenticated for.
 */
export const listModels: Client["listModels"] = (callOptions) => client.listModels(callOptions);

/**
 * Open or create a live session
 * 
 * Load a session as a live agent, or start a new one in `cwd`.
 * 
 * Idempotent for an already-loaded session: the existing live agent is
 * returned rather than a second one being created for the same file.
 */
export const openSession: Client["openSession"] = (options, callOptions) => client.openSession(options, callOptions);

/**
 * Read live session state
 * 
 * Current model, thinking level, streaming status and plan state.
 */
export const getState: Client["getState"] = (options, callOptions) => client.getState(options, callOptions);

/**
 * Read the session transcript
 * 
 * The session transcript, flattened into renderable parts.
 */
export const getTranscript: Client["getTranscript"] = (options, callOptions) => client.getTranscript(options, callOptions);

/**
 * Prompt the agent
 * 
 * Send a message. Returns as soon as the turn is scheduled; the reply
 * arrives as AG-UI frames on the session's WebSocket.
 */
export const prompt: Client["prompt"] = (options, callOptions) => client.prompt(options, callOptions);

/**
 * Abort the current turn
 * 
 * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
 */
export const abort: Client["abort"] = (options, callOptions) => client.abort(options, callOptions);

/**
 * Select a model
 * 
 * Switch the live session's model, and optionally its thinking level.
 */
export const selectModel: Client["selectModel"] = (options, callOptions) => client.selectModel(options, callOptions);

/**
 * Read the plan document
 * 
 * The plan document, its headings and the executable role tiers — the three
 * planning panes in one payload.
 */
export const getPlan: Client["getPlan"] = (options, callOptions) => client.getPlan(options, callOptions);

/**
 * Toggle plan mode
 * 
 * Turn plan mode on or off for the live session.
 */
export const setPlanMode: Client["setPlanMode"] = (options, callOptions) => client.setPlanMode(options, callOptions);

/**
 * Edit the plan document
 * 
 * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
 */
export const editPlan: Client["editPlan"] = (options, callOptions) => client.editPlan(options, callOptions);

/**
 * Resolve the plan review
 * 
 * Resolve the plan review: approve and execute, approve and compact,
 * approve into a fresh session, or refine with feedback.
 */
export const resolvePlan: Client["resolvePlan"] = (options, callOptions) => client.resolvePlan(options, callOptions);

/**
 * Render markdown to HTML
 * 
 * Render markdown with `Bun.markdown.html`.
 * 
 * The browser has no `Bun.markdown`, so every rendering in the UI —
 * transcript text, thinking blocks, the plan document — comes from here.
 */
export const renderMarkdown: Client["renderMarkdown"] = (options, callOptions) => client.renderMarkdown(options, callOptions);
