// Generated by wiz from omega.
// Every operation the document declares. Edit the document, not this file.

import type { Ack, BranchPoint, BranchRequest, BranchResult, CompactRequest, GitStatusResult, LiveState, MarkdownRequest, ModelOption, OpenSessionRequest, PlanActionRequest, PlanDocument, PlanEditRequest, PlanModeRequest, PromptRequest, QueueDropRequest, QueueEditRequest, QueuedMessage, ReadFileResult, RenameRequest, RenderedMarkdown, SelectModelRequest, ShakeRequest, SlashCommand, ThinkingRequest, Transcript, Workspace, WorkspaceFile } from "./model.ts";
import { decodeAck, decodeBranchResult, decodeGitStatusResult, decodeLiveState, decodePlanDocument, decodeReadFileResult, decodeRenderedMarkdown, decodeTranscript, encodeBranchRequest, encodeCompactRequest, encodeMarkdownRequest, encodeOpenSessionRequest, encodePlanActionRequest, encodePlanEditRequest, encodePlanModeRequest, encodePromptRequest, encodeQueueDropRequest, encodeQueueEditRequest, encodeRenameRequest, encodeSelectModelRequest, encodeShakeRequest, encodeThinkingRequest } from "./codec.ts";

/** One outgoing call, as built by a method and seen by every interceptor. */
export interface Call {
  method: string;
  url: string;
  headers: Record<string, string>;
  /** JSON text for an HTTP call, a framed protobuf message for a gRPC one. */
  body?: string | Uint8Array;
  /** Signal for cancellation or local timeout. */
  signal?: AbortSignal;
}

/** A call and what came back, before the status is judged. */
export interface CallResult {
  call: Call;
  response: Response;
}

/**
 * Per-call cancellation and deadline, the same two things a gRPC call takes.
 * There is deliberately no `headers` here: an HTTP document declares its
 * headers, so they are slots on the method rather than ambient metadata.
 */
export interface HttpCallOptions {
  /** Cancels the call. Whatever `fetch` does with an aborted signal happens. */
  signal?: AbortSignal;
  /**
   * A deadline for this call, enforced locally: the call aborts with a
   * `TimeoutError` when it passes, whatever the server is doing.
   */
  timeoutMs?: number;
}

/**
 * The caller's signal and the deadline as one signal, built per attempt so an
 * interceptor that calls `next` again gets a fresh deadline rather than one
 * that has already fired.
 */
function effectiveSignal(
  signal: AbortSignal | undefined,
  timeoutMs: number | undefined
): AbortSignal | undefined {
  const deadline =
    timeoutMs === undefined ? [] : [AbortSignal.timeout(timeoutMs)];
  return signal ? AbortSignal.any([signal, ...deadline]) : deadline[0];
}


/**
 * A wrapper around one call.
 *
 * One shape serves both protocols, so an interceptor can do the same four
 * things either side: change the call on the way in, change what comes back on
 * the way out, call `next` more than once to retry, or never call it and
 * answer from somewhere else. The call type is shared too, so an interceptor
 * that only touches the request - the common case, a token - is one generic
 * function that both sides accept.
 */
export type Interceptor<TResult> = (
  call: Call,
  next: (call: Call) => TResult
) => TResult;

/** Wraps an HTTP call. The response is raw: its status is judged afterwards. */
export type HttpInterceptor = Interceptor<Promise<CallResult>>;

/**
 * A chain per protocol, because what an interceptor gets back differs. Only the
 * protocols this document speaks are here, so an array can never be written
 * into a key nothing will read.
 */
export interface Interceptors {
  /** Outermost first: `[a, b]` runs a around b around the request. */
  http?: HttpInterceptor[];
}

/** Folds the chain right to left, so the first interceptor is the outermost. */
function chain<TResult>(
  interceptors: ReadonlyArray<Interceptor<TResult>> | undefined,
  invoke: (call: Call) => TResult
): (call: Call) => TResult {
  if (!interceptors || interceptors.length === 0) return invoke;
  return interceptors.reduceRight<(call: Call) => TResult>(
    (next, interceptor) => (call) => interceptor(call, next),
    invoke
  );
}

/**
 * The part of `fetch` this client calls, so a stub does not have to be a whole
 * one. A real `fetch` is assignable to it: it accepts wider input than this.
 */
export type FetchLike = (
  url: string,
  init: {
    method: string;
    headers: Record<string, string>;
    body?: string | Uint8Array;
    signal?: AbortSignal;
  }
) => Promise<Response>;


/**
 * An HTTP transport that executes an outgoing call.
 *
 * Symmetrical to `GrpcTransport`: a custom transport receives the `Call` and
 * returns a `Response`.
 */
export interface HttpTransport {
  call(call: Call): Promise<Response>;
}

function httpTransport(config: ClientConfig): HttpTransport {
  if (config.transport) {
    if (typeof config.transport === "function") {
      const fn = config.transport;
      return {
        call: (c) =>
          fn(c.url, {
            method: c.method,
            headers: c.headers,
            body: c.body,
            signal: c.signal,
          }),
      };
    }
    if (
      typeof config.transport === "object" &&
      "call" in config.transport &&
      !("duplex" in config.transport)
    ) {
      return config.transport;
    }
  }
  return {
    call: (c) =>
      globalThis.fetch(c.url, {
        method: c.method,
        headers: c.headers,
        body: c.body as BodyInit | undefined,
        signal: c.signal,
      }),
  };
}

export interface ClientConfig {
  /**
   * Prefix for every path. The document does not carry it: OpenAPI `servers`
   * describe environments, which is a runtime fact, not a compile-time one.
   */
  baseUrl: string;
  /**
   * Custom HTTP transport. Defaults to globalThis.fetch when omitted.
   */
  transport?: HttpTransport | FetchLike;
  /**
   * Wrappers around every call, outermost first. This is where an
   * Authorization header comes from, and where a retry or a log belongs.
   */
  interceptors?: Interceptors;
  /**
   * A deadline for every call, unless the call overrides it. Sent as
   * `grpc-timeout` where the protocol has one, and always enforced locally.
   */
  timeoutMs?: number;
}

const DEFAULTS: ClientConfig = {
  baseUrl: "",
};

/** A response outside 2xx. The parsed body is kept: that is where APIs explain. */
export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;
  readonly response: Response;

  constructor(status: number, body: unknown, response: Response) {
    super(`HTTP ${status} for ${response.url}`);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
    this.response = response;
  }
}

function encodePath(value: string | number | boolean): string {
  return encodeURIComponent(String(value));
}

function queryString(query: Record<string, unknown> | undefined): string {
  if (!query) return "";
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    // A repeated key is how every OpenAPI serialisation style spells an array.
    if (Array.isArray(value)) {
      for (const item of value) search.append(key, String(item));
      continue;
    }
    search.append(key, String(value));
  }
  const text = search.toString();
  return text ? `?${text}` : "";
}

function headerRecord(
  headers: Record<string, unknown> | undefined,
  cookie: Record<string, unknown> | undefined,
  contentType: string | undefined
): Record<string, string> {
  const record: Record<string, string> = {};
  if (contentType) record["content-type"] = contentType;

  for (const [key, value] of Object.entries(headers ?? {})) {
    if (value === undefined || value === null) continue;
    record[key] = String(value);
  }

  // Cookie parameters travel in one header, which is the only way HTTP has.
  const crumbs = Object.entries(cookie ?? {}).filter(
    ([, value]) => value !== undefined && value !== null
  );
  if (crumbs.length > 0) {
    record["cookie"] = crumbs
      .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
      .join("; ");
  }

  return record;
}

async function parseBody(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const text = await response.text();
  if (text === "") return undefined;
  const ct = (response.headers.get("content-type") ?? "").toLowerCase();
  const bun = (globalThis as any).Bun;
  if (ct.includes("jsonl") || ct.includes("json-lines") || ct.includes("x-jsonlines")) {
    try {
      return (bun?.JSONL ?? { parse: (t: string) => t.trim().split("\n").map((l: string) => JSON.parse(l)) }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("jsonc")) {
    try {
      return (bun?.JSONC ?? JSON).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("json5")) {
    try {
      return (bun?.JSON5 ?? JSON).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("yaml")) {
    try {
      return (bun?.YAML ?? { parse: (t: string) => JSON.parse(t) }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("xml")) {
    try {
      return (bun?.XML ?? { parse: (t: string) => t }).parse(text);
    } catch {
      return text;
    }
  }
  if (ct.includes("cbor")) {
    try {
      const bytes = new Uint8Array(await response.arrayBuffer());
      return typeof (globalThis as any).decodeCbor === "function" ? (globalThis as any).decodeCbor(bytes) : bytes;
    } catch {
      return text;
    }
  }
  if (ct.includes("erlang-binary") || ct.includes("etf")) {
    try {
      const bytes = new Uint8Array(await response.arrayBuffer());
      return typeof (globalThis as any).decodeErlangBinary === "function" ? (globalThis as any).decodeErlangBinary(bytes) : bytes;
    } catch {
      return text;
    }
  }
  if (ct.includes("erlang")) {
    try {
      return typeof (globalThis as any).decodeErlangText === "function" ? (globalThis as any).decodeErlangText(text) : text;
    } catch {
      return text;
    }
  }
  if (ct.includes("json")) {
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
  return text;
}

async function send(
  config: ClientConfig,
  call: Call,
  options: HttpCallOptions | undefined
): Promise<unknown> {
  const http = httpTransport(config);

  // The signal is built inside the attempt, not once per call, so an
  // interceptor that calls `next` again gets a fresh deadline rather than one
  // that has already fired. The caller's own signal spans every attempt.
  const invoke = async (outgoing: Call): Promise<CallResult> => {
    const activeCall: Call = {
      ...outgoing,
      signal: effectiveSignal(
        options?.signal,
        options?.timeoutMs ?? config.timeoutMs
      ),
    };
    return {
      call: activeCall,
      response: await http.call(activeCall),
    };
  };
  // The status is judged after the chain, so an interceptor sees the response
  // that a retry or a token refresh has to look at, not an exception.
  const settled = await chain(config.interceptors?.http, invoke)(call);

  const body = await parseBody(settled.response);
  if (!settled.response.ok) {
    throw new ApiError(settled.response.status, body, settled.response);
  }
  return body;
}

/** Call options for `listWorkspaces`. */
export type ListWorkspacesOptions = HttpCallOptions;
/** What `listWorkspaces` resolves to. */
export type ListWorkspacesResult = Workspace[];
/** Call options for `listModels`. */
export type ListModelsOptions = HttpCallOptions;
/** What `listModels` resolves to. */
export type ListModelsResult = ModelOption[];
/** Call options for `listFiles`. */
export type ListFilesOptions = { query?: { /** Workspace cwd to list files from. Defaults to the current project or server cwd. */ cwd?: string } };
/** What `listFiles` resolves to. */
export type ListFilesResult = WorkspaceFile[];
/** Call options for `getFileContent`. */
export type GetFileContentOptions = { query: { /** Relative path of the file to read. */ path: string; /** Workspace cwd to read from. Defaults to current project or server cwd. */ cwd?: string } };
/** What `getFileContent` resolves to. */
export type GetFileContentResult = ReadFileResult;
/** Call options for `getGitStatus`. */
export type GetGitStatusOptions = { query?: { /** Workspace cwd to query git status from. Defaults to the current project or server cwd. */ cwd?: string } };
/** What `getGitStatus` resolves to. */
export type GetGitStatusResult = GitStatusResult;
/** Call options for `openSession`. */
export type OpenSessionOptions = { body: OpenSessionRequest };
/** What `openSession` resolves to. */
export type OpenSessionResult = LiveState;
/** Call options for `getState`. */
export type GetStateOptions = { path: { key: string } };
/** What `getState` resolves to. */
export type GetStateResult = LiveState;
/** Call options for `getTranscript`. */
export type GetTranscriptOptions = { path: { key: string } };
/** What `getTranscript` resolves to. */
export type GetTranscriptResult = Transcript;
/** Call options for `prompt`. */
export type PromptOptions = { path: { key: string }; body: PromptRequest };
/** What `prompt` resolves to. */
export type PromptResult = Ack;
/** Call options for `abort`. */
export type AbortOptions = { path: { key: string } };
/** What `abort` resolves to. */
export type AbortResult = Ack;
/** Call options for `listQueue`. */
export type ListQueueOptions = { path: { key: string } };
/** What `listQueue` resolves to. */
export type ListQueueResult = QueuedMessage[];
/** Call options for `listCommands`. */
export type ListCommandsOptions = { path: { key: string } };
/** What `listCommands` resolves to. */
export type ListCommandsResult = SlashCommand[];
/** Call options for `editQueued`. */
export type EditQueuedOptions = { path: { key: string }; body: QueueEditRequest };
/** What `editQueued` resolves to. */
export type EditQueuedResult = QueuedMessage[];
/** Call options for `dropQueued`. */
export type DropQueuedOptions = { path: { key: string }; body: QueueDropRequest };
/** What `dropQueued` resolves to. */
export type DropQueuedResult = QueuedMessage[];
/** Call options for `stopSession`. */
export type StopSessionOptions = { path: { key: string } };
/** What `stopSession` resolves to. */
export type StopSessionResult = Ack;
/** Call options for `deleteSession`. */
export type DeleteSessionOptions = { path: { key: string } };
/** What `deleteSession` resolves to. */
export type DeleteSessionResult = Ack;
/** Call options for `selectModel`. */
export type SelectModelOptions = { path: { key: string }; body: SelectModelRequest };
/** What `selectModel` resolves to. */
export type SelectModelResult = LiveState;
/** Call options for `compactSession`. */
export type CompactSessionOptions = { path: { key: string }; body: CompactRequest };
/** What `compactSession` resolves to. */
export type CompactSessionResult = Ack;
/** Call options for `shakeSession`. */
export type ShakeSessionOptions = { path: { key: string }; body: ShakeRequest };
/** What `shakeSession` resolves to. */
export type ShakeSessionResult = Ack;
/** Call options for `setThinkingLevel`. */
export type SetThinkingLevelOptions = { path: { key: string }; body: ThinkingRequest };
/** What `setThinkingLevel` resolves to. */
export type SetThinkingLevelResult = LiveState;
/** Call options for `renameSession`. */
export type RenameSessionOptions = { path: { key: string }; body: RenameRequest };
/** What `renameSession` resolves to. */
export type RenameSessionResult = LiveState;
/** Call options for `retryTurn`. */
export type RetryTurnOptions = { path: { key: string } };
/** What `retryTurn` resolves to. */
export type RetryTurnResult = Ack;
/** Call options for `forkSession`. */
export type ForkSessionOptions = { path: { key: string } };
/** What `forkSession` resolves to. */
export type ForkSessionResult = LiveState;
/** Call options for `listBranchPoints`. */
export type ListBranchPointsOptions = { path: { key: string } };
/** What `listBranchPoints` resolves to. */
export type ListBranchPointsResult = BranchPoint[];
/** Call options for `branchSession`. */
export type BranchSessionOptions = { path: { key: string }; body: BranchRequest };
/** What `branchSession` resolves to. */
export type BranchSessionResult = BranchResult;
/** Call options for `getPlan`. */
export type GetPlanOptions = { path: { key: string } };
/** What `getPlan` resolves to. */
export type GetPlanResult = PlanDocument;
/** Call options for `setPlanMode`. */
export type SetPlanModeOptions = { path: { key: string }; body: PlanModeRequest };
/** What `setPlanMode` resolves to. */
export type SetPlanModeResult = PlanDocument;
/** Call options for `editPlan`. */
export type EditPlanOptions = { path: { key: string }; body: PlanEditRequest };
/** What `editPlan` resolves to. */
export type EditPlanResult = PlanDocument;
/** Call options for `resolvePlan`. */
export type ResolvePlanOptions = { path: { key: string }; body: PlanActionRequest };
/** What `resolvePlan` resolves to. */
export type ResolvePlanResult = Ack;
/** Call options for `renderMarkdown`. */
export type RenderMarkdownOptions = { body: MarkdownRequest };
/** What `renderMarkdown` resolves to. */
export type RenderMarkdownResult = RenderedMarkdown;

/**
 * Every operation the document declares.
 *
 * A caller that talks to one deployment can ignore this and use the
 * module-level functions below; a caller that talks to several holds one
 * client per configuration.
 */
export interface Client {
  /**
   * List workspaces and their sessions
   * 
   * Every directory with sessions on disk, each with its sessions nested.
   */
  listWorkspaces(callOptions?: HttpCallOptions): Promise<ListWorkspacesResult>;
  /**
   * List available models
   * 
   * Models the local omp install is authenticated for.
   */
  listModels(callOptions?: HttpCallOptions): Promise<ListModelsResult>;
  /** Files in a workspace directory, relative to `cwd`. */
  listFiles(options?: ListFilesOptions, callOptions?: HttpCallOptions): Promise<ListFilesResult>;
  /** Read content and metadata of a workspace file. */
  getFileContent(options: GetFileContentOptions, callOptions?: HttpCallOptions): Promise<GetFileContentResult>;
  /** Git status for a workspace directory. */
  getGitStatus(options?: GetGitStatusOptions, callOptions?: HttpCallOptions): Promise<GetGitStatusResult>;
  /**
   * Open or create a live session
   * 
   * Load a session as a live agent, or start a new one in `cwd`.
   * 
   * Idempotent for an already-loaded session: the existing live agent is
   * returned rather than a second one being created for the same file.
   */
  openSession(options: OpenSessionOptions, callOptions?: HttpCallOptions): Promise<OpenSessionResult>;
  /**
   * Read live session state
   * 
   * Current model, thinking level, streaming status and plan state.
   */
  getState(options: GetStateOptions, callOptions?: HttpCallOptions): Promise<GetStateResult>;
  /**
   * Read the session transcript
   * 
   * The session transcript, flattened into renderable parts.
   */
  getTranscript(options: GetTranscriptOptions, callOptions?: HttpCallOptions): Promise<GetTranscriptResult>;
  /**
   * Prompt the agent
   * 
   * Send a message. Returns as soon as the turn is scheduled; the reply
   * arrives as AG-UI frames on the session's WebSocket.
   */
  prompt(options: PromptOptions, callOptions?: HttpCallOptions): Promise<PromptResult>;
  /**
   * Abort the current turn
   * 
   * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
   */
  abort(options: AbortOptions, callOptions?: HttpCallOptions): Promise<AbortResult>;
  /**
   * List queued messages
   * 
   * The user messages waiting to be delivered, steering lane first.
   * 
   * Empty whenever the session is idle: a queue only exists while a turn is
   * in flight to queue behind.
   */
  listQueue(options: ListQueueOptions, callOptions?: HttpCallOptions): Promise<ListQueueResult>;
  /**
   * List MCP slash commands
   * 
   * Slash commands MCP servers contribute to this session.
   * 
   * Session-scoped rather than global: which servers are connected, and so
   * which prompts exist, is a property of the agent, not of the install.
   */
  listCommands(options: ListCommandsOptions, callOptions?: HttpCallOptions): Promise<ListCommandsResult>;
  /**
   * Edit a queued message
   * 
   * Rewrite a queued message in place, keeping its lane and position.
   * 
   * Returns the queue as it stands afterwards, so the caller never has to
   * guess what the agent drained in the meantime.
   */
  editQueued(options: EditQueuedOptions, callOptions?: HttpCallOptions): Promise<EditQueuedResult>;
  /**
   * Drop a queued message
   * 
   * Drop a queued message before it is delivered.
   */
  dropQueued(options: DropQueuedOptions, callOptions?: HttpCallOptions): Promise<DropQueuedResult>;
  /**
   * Stop a live session
   * 
   * Stop and release a live agent session from memory.
   */
  stopSession(options: StopSessionOptions, callOptions?: HttpCallOptions): Promise<StopSessionResult>;
  /**
   * Delete a session from disk
   * 
   * Delete a session file and its artifacts from disk, disposing it first if live.
   */
  deleteSession(options: DeleteSessionOptions, callOptions?: HttpCallOptions): Promise<DeleteSessionResult>;
  /**
   * Select a model
   * 
   * Switch the live session's model, and optionally its thinking level.
   */
  selectModel(options: SelectModelOptions, callOptions?: HttpCallOptions): Promise<SelectModelResult>;
  /**
   * Compact the session context
   * 
   * Compact the session context now, mirroring omp's `/compact`.
   */
  compactSession(options: CompactSessionOptions, callOptions?: HttpCallOptions): Promise<CompactSessionResult>;
  /**
   * Shake heavy content out of context
   * 
   * Drop heavy content (tool results, large blocks, or images) from context.
   */
  shakeSession(options: ShakeSessionOptions, callOptions?: HttpCallOptions): Promise<ShakeSessionResult>;
  /**
   * Set the thinking level
   * 
   * Set the session's thinking level without changing the model.
   */
  setThinkingLevel(options: SetThinkingLevelOptions, callOptions?: HttpCallOptions): Promise<SetThinkingLevelResult>;
  /**
   * Rename the session
   * 
   * Rename the session, as omp's `/rename` does.
   */
  renameSession(options: RenameSessionOptions, callOptions?: HttpCallOptions): Promise<RenameSessionResult>;
  /**
   * Retry the last failed turn
   * 
   * Re-run the last failed or aborted turn. The retried turn streams over the
   * session's WebSocket, so this returns as soon as it is scheduled.
   */
  retryTurn(options: RetryTurnOptions, callOptions?: HttpCallOptions): Promise<RetryTurnResult>;
  /**
   * Fork the session
   * 
   * Copy this session, transcript and artifacts included, into a new one and
   * continue in the copy. The original file stays on disk untouched.
   */
  forkSession(options: ForkSessionOptions, callOptions?: HttpCallOptions): Promise<ForkSessionResult>;
  /**
   * List branch points
   * 
   * The user messages this session can branch from, oldest first.
   */
  listBranchPoints(options: ListBranchPointsOptions, callOptions?: HttpCallOptions): Promise<ListBranchPointsResult>;
  /**
   * Branch from an earlier message
   * 
   * Restart the conversation from an earlier user message: omp writes a new
   * session containing everything up to that message's parent and continues
   * there, returning the message text so the composer can be pre-filled.
   */
  branchSession(options: BranchSessionOptions, callOptions?: HttpCallOptions): Promise<BranchSessionResult>;
  /**
   * Read the plan document
   * 
   * The plan document, its headings and the executable role tiers — the three
   * planning panes in one payload.
   */
  getPlan(options: GetPlanOptions, callOptions?: HttpCallOptions): Promise<GetPlanResult>;
  /**
   * Toggle plan mode
   * 
   * Turn plan mode on or off for the live session.
   */
  setPlanMode(options: SetPlanModeOptions, callOptions?: HttpCallOptions): Promise<SetPlanModeResult>;
  /**
   * Edit the plan document
   * 
   * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
   */
  editPlan(options: EditPlanOptions, callOptions?: HttpCallOptions): Promise<EditPlanResult>;
  /**
   * Resolve the plan review
   * 
   * Resolve the plan review: approve and execute, approve and compact,
   * approve into a fresh session, or refine with feedback.
   */
  resolvePlan(options: ResolvePlanOptions, callOptions?: HttpCallOptions): Promise<ResolvePlanResult>;
  /**
   * Render markdown to HTML
   * 
   * Render markdown with `Bun.markdown.html`.
   * 
   * The browser has no `Bun.markdown`, so every rendering in the UI —
   * transcript text, thinking blocks, the plan document — comes from here.
   */
  renderMarkdown(options: RenderMarkdownOptions, callOptions?: HttpCallOptions): Promise<RenderMarkdownResult>;
}

/**
 * A client bound to its own configuration.
 *
 * Two tenants, two base URLs or two credentials are two clients; nothing is
 * shared between them, and the module-level default is just one more.
 */
export function createClient(overrides: Partial<ClientConfig> = {}): Client {
  const config: ClientConfig = { ...DEFAULTS, ...overrides };

  return {
    async listWorkspaces(callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/workspaces`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as Workspace[];
    },
    async listModels(callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/models`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as ModelOption[];
    },
    async listFiles(options, callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/files${queryString(options?.query)}`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as WorkspaceFile[];
    },
    async getFileContent(options, callOptions) {
      return decodeReadFileResult(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/files/content${queryString(options.query)}`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as ReadFileResult;
    },
    async getGitStatus(options, callOptions) {
      return decodeGitStatusResult(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/git/status${queryString(options?.query)}`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as GitStatusResult;
    },
    async openSession(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeOpenSessionRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async getState(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/state`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as LiveState;
    },
    async getTranscript(options, callOptions) {
      return decodeTranscript(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/transcript`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Transcript;
    },
    async prompt(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/prompt`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePromptRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async abort(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/abort`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Ack;
    },
    async listQueue(options, callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/queue`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as QueuedMessage[];
    },
    async listCommands(options, callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/commands`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as SlashCommand[];
    },
    async editQueued(options, callOptions) {
      return (await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/queue/edit`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeQueueEditRequest(options.body),
      }, callOptions)) as QueuedMessage[];
    },
    async dropQueued(options, callOptions) {
      return (await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/queue/drop`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeQueueDropRequest(options.body),
      }, callOptions)) as QueuedMessage[];
    },
    async stopSession(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/stop`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Ack;
    },
    async deleteSession(options, callOptions) {
      return decodeAck(await send(config, {
        method: "DELETE",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Ack;
    },
    async selectModel(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/model`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeSelectModelRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async compactSession(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/compact`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeCompactRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async shakeSession(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/shake`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeShakeRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async setThinkingLevel(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/thinking`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeThinkingRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async renameSession(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/title`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeRenameRequest(options.body),
      }, callOptions) as string) as LiveState;
    },
    async retryTurn(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/retry`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as Ack;
    },
    async forkSession(options, callOptions) {
      return decodeLiveState(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/fork`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as LiveState;
    },
    async listBranchPoints(options, callOptions) {
      return (await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/branch-points`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions)) as BranchPoint[];
    },
    async branchSession(options, callOptions) {
      return decodeBranchResult(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/branch`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeBranchRequest(options.body),
      }, callOptions) as string) as BranchResult;
    },
    async getPlan(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "GET",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan`,
        headers: headerRecord(undefined, undefined, undefined),
      }, callOptions) as string) as PlanDocument;
    },
    async setPlanMode(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/mode`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanModeRequest(options.body),
      }, callOptions) as string) as PlanDocument;
    },
    async editPlan(options, callOptions) {
      return decodePlanDocument(await send(config, {
        method: "PUT",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/document`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanEditRequest(options.body),
      }, callOptions) as string) as PlanDocument;
    },
    async resolvePlan(options, callOptions) {
      return decodeAck(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/sessions/${encodePath(options.path.key)}/plan/action`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodePlanActionRequest(options.body),
      }, callOptions) as string) as Ack;
    },
    async renderMarkdown(options, callOptions) {
      return decodeRenderedMarkdown(await send(config, {
        method: "POST",
        url: `${config.baseUrl}/api/markdown`,
        headers: headerRecord(undefined, undefined, "application/json"),
        body: encodeMarkdownRequest(options.body),
      }, callOptions) as string) as RenderedMarkdown;
    },
  };
}

let defaults: ClientConfig = { ...DEFAULTS };
let client: Client = createClient();

/**
 * Merges into the configuration the module-level functions use, so a base
 * URL and an interceptor can be set from different places.
 */
export function configure(next: Partial<ClientConfig>): void {
  defaults = { ...defaults, ...next };
  client = createClient(defaults);
}

export function currentConfig(): ClientConfig {
  return defaults;
}

/** The client `configure()` maintains, which hooks and other consumers default to. */
export function defaultClient(): Client {
  return client;
}

/**
 * List workspaces and their sessions
 * 
 * Every directory with sessions on disk, each with its sessions nested.
 */
export const listWorkspaces: Client["listWorkspaces"] = (callOptions) => client.listWorkspaces(callOptions);

/**
 * List available models
 * 
 * Models the local omp install is authenticated for.
 */
export const listModels: Client["listModels"] = (callOptions) => client.listModels(callOptions);

/** Files in a workspace directory, relative to `cwd`. */
export const listFiles: Client["listFiles"] = (options, callOptions) => client.listFiles(options, callOptions);

/** Read content and metadata of a workspace file. */
export const getFileContent: Client["getFileContent"] = (options, callOptions) => client.getFileContent(options, callOptions);

/** Git status for a workspace directory. */
export const getGitStatus: Client["getGitStatus"] = (options, callOptions) => client.getGitStatus(options, callOptions);

/**
 * Open or create a live session
 * 
 * Load a session as a live agent, or start a new one in `cwd`.
 * 
 * Idempotent for an already-loaded session: the existing live agent is
 * returned rather than a second one being created for the same file.
 */
export const openSession: Client["openSession"] = (options, callOptions) => client.openSession(options, callOptions);

/**
 * Read live session state
 * 
 * Current model, thinking level, streaming status and plan state.
 */
export const getState: Client["getState"] = (options, callOptions) => client.getState(options, callOptions);

/**
 * Read the session transcript
 * 
 * The session transcript, flattened into renderable parts.
 */
export const getTranscript: Client["getTranscript"] = (options, callOptions) => client.getTranscript(options, callOptions);

/**
 * Prompt the agent
 * 
 * Send a message. Returns as soon as the turn is scheduled; the reply
 * arrives as AG-UI frames on the session's WebSocket.
 */
export const prompt: Client["prompt"] = (options, callOptions) => client.prompt(options, callOptions);

/**
 * Abort the current turn
 * 
 * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
 */
export const abort: Client["abort"] = (options, callOptions) => client.abort(options, callOptions);

/**
 * List queued messages
 * 
 * The user messages waiting to be delivered, steering lane first.
 * 
 * Empty whenever the session is idle: a queue only exists while a turn is
 * in flight to queue behind.
 */
export const listQueue: Client["listQueue"] = (options, callOptions) => client.listQueue(options, callOptions);

/**
 * List MCP slash commands
 * 
 * Slash commands MCP servers contribute to this session.
 * 
 * Session-scoped rather than global: which servers are connected, and so
 * which prompts exist, is a property of the agent, not of the install.
 */
export const listCommands: Client["listCommands"] = (options, callOptions) => client.listCommands(options, callOptions);

/**
 * Edit a queued message
 * 
 * Rewrite a queued message in place, keeping its lane and position.
 * 
 * Returns the queue as it stands afterwards, so the caller never has to
 * guess what the agent drained in the meantime.
 */
export const editQueued: Client["editQueued"] = (options, callOptions) => client.editQueued(options, callOptions);

/**
 * Drop a queued message
 * 
 * Drop a queued message before it is delivered.
 */
export const dropQueued: Client["dropQueued"] = (options, callOptions) => client.dropQueued(options, callOptions);

/**
 * Stop a live session
 * 
 * Stop and release a live agent session from memory.
 */
export const stopSession: Client["stopSession"] = (options, callOptions) => client.stopSession(options, callOptions);

/**
 * Delete a session from disk
 * 
 * Delete a session file and its artifacts from disk, disposing it first if live.
 */
export const deleteSession: Client["deleteSession"] = (options, callOptions) => client.deleteSession(options, callOptions);

/**
 * Select a model
 * 
 * Switch the live session's model, and optionally its thinking level.
 */
export const selectModel: Client["selectModel"] = (options, callOptions) => client.selectModel(options, callOptions);

/**
 * Compact the session context
 * 
 * Compact the session context now, mirroring omp's `/compact`.
 */
export const compactSession: Client["compactSession"] = (options, callOptions) => client.compactSession(options, callOptions);

/**
 * Shake heavy content out of context
 * 
 * Drop heavy content (tool results, large blocks, or images) from context.
 */
export const shakeSession: Client["shakeSession"] = (options, callOptions) => client.shakeSession(options, callOptions);

/**
 * Set the thinking level
 * 
 * Set the session's thinking level without changing the model.
 */
export const setThinkingLevel: Client["setThinkingLevel"] = (options, callOptions) => client.setThinkingLevel(options, callOptions);

/**
 * Rename the session
 * 
 * Rename the session, as omp's `/rename` does.
 */
export const renameSession: Client["renameSession"] = (options, callOptions) => client.renameSession(options, callOptions);

/**
 * Retry the last failed turn
 * 
 * Re-run the last failed or aborted turn. The retried turn streams over the
 * session's WebSocket, so this returns as soon as it is scheduled.
 */
export const retryTurn: Client["retryTurn"] = (options, callOptions) => client.retryTurn(options, callOptions);

/**
 * Fork the session
 * 
 * Copy this session, transcript and artifacts included, into a new one and
 * continue in the copy. The original file stays on disk untouched.
 */
export const forkSession: Client["forkSession"] = (options, callOptions) => client.forkSession(options, callOptions);

/**
 * List branch points
 * 
 * The user messages this session can branch from, oldest first.
 */
export const listBranchPoints: Client["listBranchPoints"] = (options, callOptions) => client.listBranchPoints(options, callOptions);

/**
 * Branch from an earlier message
 * 
 * Restart the conversation from an earlier user message: omp writes a new
 * session containing everything up to that message's parent and continues
 * there, returning the message text so the composer can be pre-filled.
 */
export const branchSession: Client["branchSession"] = (options, callOptions) => client.branchSession(options, callOptions);

/**
 * Read the plan document
 * 
 * The plan document, its headings and the executable role tiers — the three
 * planning panes in one payload.
 */
export const getPlan: Client["getPlan"] = (options, callOptions) => client.getPlan(options, callOptions);

/**
 * Toggle plan mode
 * 
 * Turn plan mode on or off for the live session.
 */
export const setPlanMode: Client["setPlanMode"] = (options, callOptions) => client.setPlanMode(options, callOptions);

/**
 * Edit the plan document
 * 
 * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
 */
export const editPlan: Client["editPlan"] = (options, callOptions) => client.editPlan(options, callOptions);

/**
 * Resolve the plan review
 * 
 * Resolve the plan review: approve and execute, approve and compact,
 * approve into a fresh session, or refine with feedback.
 */
export const resolvePlan: Client["resolvePlan"] = (options, callOptions) => client.resolvePlan(options, callOptions);

/**
 * Render markdown to HTML
 * 
 * Render markdown with `Bun.markdown.html`.
 * 
 * The browser has no `Bun.markdown`, so every rendering in the UI —
 * transcript text, thinking blocks, the plan document — comes from here.
 */
export const renderMarkdown: Client["renderMarkdown"] = (options, callOptions) => client.renderMarkdown(options, callOptions);
