// Generated by wiz from omega.
// Wire encoders and decoders. Edit the document, not this file.

import type { Ack, BranchRequest, BranchResult, CompactRequest, LiveState, MarkdownRequest, OpenSessionRequest, PlanActionRequest, PlanDocument, PlanEditRequest, PlanModeRequest, Problem, PromptRequest, QueueDropRequest, QueueEditRequest, RenameRequest, RenderedMarkdown, SelectModelRequest, ShakeRequest, ThinkingRequest, Transcript } from "./model.ts";

export function encodeOpenSessionRequest(val: OpenSessionRequest): string {
  return JSON.stringify(val);
}

export function decodeOpenSessionRequest(raw: string): OpenSessionRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeLiveState(val: LiveState): string {
  return JSON.stringify(val);
}

export function decodeLiveState(raw: string): LiveState {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeProblem(val: Problem): string {
  return JSON.stringify(val);
}

export function decodeProblem(raw: string): Problem {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeTranscript(val: Transcript): string {
  return JSON.stringify(val);
}

export function decodeTranscript(raw: string): Transcript {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePromptRequest(val: PromptRequest): string {
  return JSON.stringify(val);
}

export function decodePromptRequest(raw: string): PromptRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeAck(val: Ack): string {
  return JSON.stringify(val);
}

export function decodeAck(raw: string): Ack {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeQueueEditRequest(val: QueueEditRequest): string {
  return JSON.stringify(val);
}

export function decodeQueueEditRequest(raw: string): QueueEditRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeQueueDropRequest(val: QueueDropRequest): string {
  return JSON.stringify(val);
}

export function decodeQueueDropRequest(raw: string): QueueDropRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeSelectModelRequest(val: SelectModelRequest): string {
  return JSON.stringify(val);
}

export function decodeSelectModelRequest(raw: string): SelectModelRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeCompactRequest(val: CompactRequest): string {
  return JSON.stringify(val);
}

export function decodeCompactRequest(raw: string): CompactRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeShakeRequest(val: ShakeRequest): string {
  return JSON.stringify(val);
}

export function decodeShakeRequest(raw: string): ShakeRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeThinkingRequest(val: ThinkingRequest): string {
  return JSON.stringify(val);
}

export function decodeThinkingRequest(raw: string): ThinkingRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeRenameRequest(val: RenameRequest): string {
  return JSON.stringify(val);
}

export function decodeRenameRequest(raw: string): RenameRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBranchRequest(val: BranchRequest): string {
  return JSON.stringify(val);
}

export function decodeBranchRequest(raw: string): BranchRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBranchResult(val: BranchResult): string {
  return JSON.stringify(val);
}

export function decodeBranchResult(raw: string): BranchResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanDocument(val: PlanDocument): string {
  return JSON.stringify(val);
}

export function decodePlanDocument(raw: string): PlanDocument {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanModeRequest(val: PlanModeRequest): string {
  return JSON.stringify(val);
}

export function decodePlanModeRequest(raw: string): PlanModeRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanEditRequest(val: PlanEditRequest): string {
  return JSON.stringify(val);
}

export function decodePlanEditRequest(raw: string): PlanEditRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanActionRequest(val: PlanActionRequest): string {
  return JSON.stringify(val);
}

export function decodePlanActionRequest(raw: string): PlanActionRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeMarkdownRequest(val: MarkdownRequest): string {
  return JSON.stringify(val);
}

export function decodeMarkdownRequest(raw: string): MarkdownRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeRenderedMarkdown(val: RenderedMarkdown): string {
  return JSON.stringify(val);
}

export function decodeRenderedMarkdown(raw: string): RenderedMarkdown {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}
