// Generated by wiz from omega.
// Wire encoders and decoders. Edit the document, not this file.

import type { A2uiDismissRequest, Ack, AddMcpServerRequest, BranchRequest, BranchResult, BtwRequest, BtwResult, CancelJobRequest, CompactRequest, DeleteRuleRequest, ForceToolRequest, GitStatusResult, ListJobsResult, ListMcpServersResult, ListProcessesResult, ListRulesResult, ListToolsResult, LiveState, MarkdownRequest, OmfgAnalyzeRequest, OmfgRuleCandidate, OmfgSaveRequest, OpenSessionRequest, PlanActionRequest, PlanDocument, PlanEditRequest, PlanModeRequest, Problem, ProcessActionRequest, PromptRequest, QueueDropRequest, QueueEditRequest, ReadFileResult, RemoveMcpServerRequest, RenameRequest, RenderedMarkdown, SelectModelRequest, ShakeRequest, SignalProcessRequest, TestMcpServerRequest, TestMcpServerResult, ThinkingRequest, Transcript } from "./model.ts";

export function encodeReadFileResult(val: ReadFileResult): string {
  return JSON.stringify(val);
}

export function decodeReadFileResult(raw: string): ReadFileResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeProblem(val: Problem): string {
  return JSON.stringify(val);
}

export function decodeProblem(raw: string): Problem {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeGitStatusResult(val: GitStatusResult): string {
  return JSON.stringify(val);
}

export function decodeGitStatusResult(raw: string): GitStatusResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeOpenSessionRequest(val: OpenSessionRequest): string {
  return JSON.stringify(val);
}

export function decodeOpenSessionRequest(raw: string): OpenSessionRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeLiveState(val: LiveState): string {
  return JSON.stringify(val);
}

export function decodeLiveState(raw: string): LiveState {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeTranscript(val: Transcript): string {
  return JSON.stringify(val);
}

export function decodeTranscript(raw: string): Transcript {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePromptRequest(val: PromptRequest): string {
  return JSON.stringify(val);
}

export function decodePromptRequest(raw: string): PromptRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeAck(val: Ack): string {
  return JSON.stringify(val);
}

export function decodeAck(raw: string): Ack {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBtwRequest(val: BtwRequest): string {
  return JSON.stringify(val);
}

export function decodeBtwRequest(raw: string): BtwRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBtwResult(val: BtwResult): string {
  return JSON.stringify(val);
}

export function decodeBtwResult(raw: string): BtwResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeOmfgAnalyzeRequest(val: OmfgAnalyzeRequest): string {
  return JSON.stringify(val);
}

export function decodeOmfgAnalyzeRequest(raw: string): OmfgAnalyzeRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeOmfgRuleCandidate(val: OmfgRuleCandidate): string {
  return JSON.stringify(val);
}

export function decodeOmfgRuleCandidate(raw: string): OmfgRuleCandidate {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeOmfgSaveRequest(val: OmfgSaveRequest): string {
  return JSON.stringify(val);
}

export function decodeOmfgSaveRequest(raw: string): OmfgSaveRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeA2uiDismissRequest(val: A2uiDismissRequest): string {
  return JSON.stringify(val);
}

export function decodeA2uiDismissRequest(raw: string): A2uiDismissRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeListMcpServersResult(val: ListMcpServersResult): string {
  return JSON.stringify(val);
}

export function decodeListMcpServersResult(raw: string): ListMcpServersResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeTestMcpServerRequest(val: TestMcpServerRequest): string {
  return JSON.stringify(val);
}

export function decodeTestMcpServerRequest(raw: string): TestMcpServerRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeTestMcpServerResult(val: TestMcpServerResult): string {
  return JSON.stringify(val);
}

export function decodeTestMcpServerResult(raw: string): TestMcpServerResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeListToolsResult(val: ListToolsResult): string {
  return JSON.stringify(val);
}

export function decodeListToolsResult(raw: string): ListToolsResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeForceToolRequest(val: ForceToolRequest): string {
  return JSON.stringify(val);
}

export function decodeForceToolRequest(raw: string): ForceToolRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeListRulesResult(val: ListRulesResult): string {
  return JSON.stringify(val);
}

export function decodeListRulesResult(raw: string): ListRulesResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeDeleteRuleRequest(val: DeleteRuleRequest): string {
  return JSON.stringify(val);
}

export function decodeDeleteRuleRequest(raw: string): DeleteRuleRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeAddMcpServerRequest(val: AddMcpServerRequest): string {
  return JSON.stringify(val);
}

export function decodeAddMcpServerRequest(raw: string): AddMcpServerRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeRemoveMcpServerRequest(val: RemoveMcpServerRequest): string {
  return JSON.stringify(val);
}

export function decodeRemoveMcpServerRequest(raw: string): RemoveMcpServerRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeListJobsResult(val: ListJobsResult): string {
  return JSON.stringify(val);
}

export function decodeListJobsResult(raw: string): ListJobsResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeCancelJobRequest(val: CancelJobRequest): string {
  return JSON.stringify(val);
}

export function decodeCancelJobRequest(raw: string): CancelJobRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeListProcessesResult(val: ListProcessesResult): string {
  return JSON.stringify(val);
}

export function decodeListProcessesResult(raw: string): ListProcessesResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeSignalProcessRequest(val: SignalProcessRequest): string {
  return JSON.stringify(val);
}

export function decodeSignalProcessRequest(raw: string): SignalProcessRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeProcessActionRequest(val: ProcessActionRequest): string {
  return JSON.stringify(val);
}

export function decodeProcessActionRequest(raw: string): ProcessActionRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeQueueEditRequest(val: QueueEditRequest): string {
  return JSON.stringify(val);
}

export function decodeQueueEditRequest(raw: string): QueueEditRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeQueueDropRequest(val: QueueDropRequest): string {
  return JSON.stringify(val);
}

export function decodeQueueDropRequest(raw: string): QueueDropRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeSelectModelRequest(val: SelectModelRequest): string {
  return JSON.stringify(val);
}

export function decodeSelectModelRequest(raw: string): SelectModelRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeCompactRequest(val: CompactRequest): string {
  return JSON.stringify(val);
}

export function decodeCompactRequest(raw: string): CompactRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeShakeRequest(val: ShakeRequest): string {
  return JSON.stringify(val);
}

export function decodeShakeRequest(raw: string): ShakeRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeThinkingRequest(val: ThinkingRequest): string {
  return JSON.stringify(val);
}

export function decodeThinkingRequest(raw: string): ThinkingRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeRenameRequest(val: RenameRequest): string {
  return JSON.stringify(val);
}

export function decodeRenameRequest(raw: string): RenameRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBranchRequest(val: BranchRequest): string {
  return JSON.stringify(val);
}

export function decodeBranchRequest(raw: string): BranchRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeBranchResult(val: BranchResult): string {
  return JSON.stringify(val);
}

export function decodeBranchResult(raw: string): BranchResult {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanDocument(val: PlanDocument): string {
  return JSON.stringify(val);
}

export function decodePlanDocument(raw: string): PlanDocument {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanModeRequest(val: PlanModeRequest): string {
  return JSON.stringify(val);
}

export function decodePlanModeRequest(raw: string): PlanModeRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanEditRequest(val: PlanEditRequest): string {
  return JSON.stringify(val);
}

export function decodePlanEditRequest(raw: string): PlanEditRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodePlanActionRequest(val: PlanActionRequest): string {
  return JSON.stringify(val);
}

export function decodePlanActionRequest(raw: string): PlanActionRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeMarkdownRequest(val: MarkdownRequest): string {
  return JSON.stringify(val);
}

export function decodeMarkdownRequest(raw: string): MarkdownRequest {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export function encodeRenderedMarkdown(val: RenderedMarkdown): string {
  return JSON.stringify(val);
}

export function decodeRenderedMarkdown(raw: string): RenderedMarkdown {
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}
