// Generated by wiz from omega.
// Types the API exchanges. Edit the document, not this file.

/** A failed request. */
export interface Problem {
  status: number;
  detail: string;
}

/** A directory that has at least one omp session on disk. */
export interface Workspace {
  cwd: string;
  name: string;
  sessions: SessionSummary[];
  modified: string;
  exists: boolean;
}

/** One persisted session, as listed from disk without loading its transcript. */
export interface SessionSummary {
  path: string;
  id: string;
  cwd: string;
  title?: string;
  created: string;
  modified: string;
  messageCount: number;
  size: number;
  firstMessage: string;
  status: SessionStatus;
  live: boolean;
}

/**
 * Coarse lifecycle status of a persisted session, mirroring omp's own
 * `SessionStatus` union so the badge in the UI means what omp means.
 */
export type SessionStatus = "complete" | "interrupted" | "aborted" | "error" | "pending" | "unknown";

/** A model the local omp install is authenticated for. */
export interface ModelOption {
  provider: string;
  id: string;
  name: string;
  ref: string;
  reasoning: boolean;
  contextWindow: number;
}

/** Which session to load as a live agent. */
export interface OpenSessionRequest {
  sessionPath?: string;
  cwd?: string;
}

/** Everything the chat header and composer need about a live session. */
export interface LiveState {
  key: string;
  sessionFile: string;
  cwd: string;
  title?: string;
  model: string;
  modelName: string;
  thinkingLevel: ThinkingLevel;
  streaming: boolean;
  queued: number;
  contextUsage?: ContextUsage;
  plan?: PlanState;
  todos?: TodoPhase[];
}

/** omp thinking levels, in ascending order of budget. */
export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

/** Context-window consumption for the live session. */
export interface ContextUsage {
  tokens: number;
  contextWindow: number;
  percent: number;
}

/** Plan-mode status carried alongside live session state. */
export interface PlanState {
  enabled: boolean;
  planFilePath: string;
  awaitingApproval: boolean;
  title?: string;
}

/** A logical grouping of tasks in the todo list. */
export interface TodoPhase {
  name: string;
  tasks: TodoTask[];
}

/** A single tracked task. */
export interface TodoTask {
  content: string;
  status: TodoTaskStatus;
  blocker?: string;
}

/** Lifecycle status of a task in the todo list. */
export type TodoTaskStatus = "pending" | "in_progress" | "completed" | "abandoned" | "blocked";

/** A transcript page. */
export interface Transcript {
  key: string;
  messages: TranscriptMessage[];
}

/** A transcript entry, flattened for rendering. */
export interface TranscriptMessage {
  id: string;
  role: "user" | "assistant" | "toolResult" | "custom";
  parts: MessagePart[];
  timestamp?: string;
}

/**
 * One renderable piece of a message. `text` and `thinking` carry markdown in
 * `text`; `toolCall` carries the call; `toolResult` carries its outcome.
 */
export interface MessagePart {
  kind: "toolResult" | "text" | "thinking" | "toolCall";
  text: string;
  toolName?: string;
  toolCallId?: string;
  args?: string;
  isError?: false | true;
}

/** A message to send to the agent. */
export interface PromptRequest {
  message: string;
  deliverAs?: "steer" | "followUp";
}

/** An operation that reports only success. */
export interface Ack {
  ok: boolean;
  detail?: string;
  sessionKey?: string;
}

/** Model to switch the live session to. */
export interface SelectModelRequest {
  ref: string;
  thinkingLevel?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
}

/** The plan document plus everything the three planning panes render. */
export interface PlanDocument {
  enabled: boolean;
  planFilePath: string;
  title?: string;
  awaitingApproval: boolean;
  content: string;
  html: string;
  sections: PlanSection[];
  tiers: PlanTier[];
  keepContextDisabled: boolean;
}

/** One heading in the plan document, for the left-hand table of contents. */
export interface PlanSection {
  id: string;
  title: string;
  level: number;
  line: number;
}

/** One configured role model the approved plan can be executed with. */
export interface PlanTier {
  role: string;
  ref: string;
  name: string;
}

/** Whether plan mode should be on. */
export interface PlanModeRequest {
  enabled: boolean;
}

/** A hand-edited plan document. */
export interface PlanEditRequest {
  content: string;
}

/** A decision from the plan actions panel. */
export interface PlanActionRequest {
  action: PlanAction;
  feedback?: string;
  tier?: string;
}

/**
 * The four decisions omp's plan review offers, matching the option list in
 * `InteractiveMode.handlePlanApproval` one-for-one.
 * 
 * - `execute` — "Approve and execute": `preserveContext: false`, so execution
 *   starts from a fresh context seeded with the plan artifact.
 * - `compact` — "Approve and compact context": distill the planning transcript,
 *   then execute.
 * - `keep` — "Approve and keep context": execute with the planning transcript
 *   intact. omp disables this when the context is already too full.
 * - `refine` — "Refine plan": stay in plan mode and re-prompt the model with
 *   `feedback`.
 */
export type PlanAction = "execute" | "compact" | "keep" | "refine";

/** Markdown to render. */
export interface MarkdownRequest {
  text: string;
}

/** Rendered markdown, produced by `Bun.markdown.html` on the server. */
export interface RenderedMarkdown {
  html: string;
}
