// Generated by wiz from omega.
// Types the API exchanges. Edit the document, not this file.

/** A failed request. */
export interface Problem {
  status: number;
  detail: string;
}

/** A directory that has at least one omp session on disk. */
export interface Workspace {
  cwd: string;
  name: string;
  sessions: SessionSummary[];
  modified: string;
  exists: boolean;
}

/** One persisted session, as listed from disk without loading its transcript. */
export interface SessionSummary {
  path: string;
  id: string;
  cwd: string;
  title?: string;
  created: string;
  modified: string;
  messageCount: number;
  size: number;
  firstMessage: string;
  status: SessionStatus;
  live: boolean;
}

/**
 * Coarse lifecycle status of a persisted session, mirroring omp's own
 * `SessionStatus` union so the badge in the UI means what omp means.
 */
export type SessionStatus = "complete" | "interrupted" | "aborted" | "error" | "pending" | "unknown";

/** A model the local omp install is authenticated for. */
export interface ModelOption {
  provider: string;
  id: string;
  name: string;
  ref: string;
  reasoning: boolean;
  contextWindow: number;
}

export type WorkspaceFile = string;

/** File content and metadata. */
export interface ReadFileResult {
  path: string;
  size: number;
  mimeType: string;
  isBinary: boolean;
  isImage: boolean;
  content?: string;
  dataUrl?: string;
}

/** Summary of git workspace status. */
export interface GitStatusResult {
  branch?: string;
  clean: boolean;
  files: Record<string, GitFileStatus>;
}

/** Git change classification for a single workspace file. */
export interface GitFileStatus {
  path: string;
  origPath?: string;
  status: "modified" | "untracked" | "added" | "deleted" | "renamed" | "copied" | "conflict" | "ignored";
  marker: string;
  staged: boolean;
  unstaged: boolean;
}

/** Which session to load as a live agent. */
export interface OpenSessionRequest {
  sessionPath?: string;
  cwd?: string;
}

/** Everything the chat header and composer need about a live session. */
export interface LiveState {
  key: string;
  sessionFile: string;
  cwd: string;
  title?: string;
  model: string;
  modelName: string;
  thinkingLevel: ThinkingLevel;
  streaming: boolean;
  queued: number;
  contextUsage?: ContextUsage;
  plan?: PlanState;
  todos?: TodoPhase[];
  subagents?: SubagentTask[];
  lastError?: string;
}

/** omp thinking levels, in ascending order of budget. */
export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

/** Context-window consumption for the live session. */
export interface ContextUsage {
  tokens: number;
  contextWindow: number;
  percent: number;
}

/** Plan-mode status carried alongside live session state. */
export interface PlanState {
  enabled: boolean;
  planFilePath: string;
  awaitingApproval: boolean;
  title?: string;
}

/** A logical grouping of tasks in the todo list. */
export interface TodoPhase {
  name: string;
  tasks: TodoTask[];
}

/** A single tracked task. */
export interface TodoTask {
  content: string;
  status: TodoTaskStatus;
  blocker?: string;
}

/** Lifecycle status of a task in the todo list. */
export type TodoTaskStatus = "pending" | "in_progress" | "completed" | "abandoned" | "blocked";

/** A subagent task spawned by the session. */
export interface SubagentTask {
  id: string;
  agent: string;
  description?: string;
  status: SubagentStatus;
  startedAt: number;
  completedAt?: number;
  error?: string;
}

/** Lifecycle status of a spawned subagent. */
export type SubagentStatus = "aborted" | "completed" | "running" | "failed";

/** A transcript page. */
export interface Transcript {
  key: string;
  messages: TranscriptMessage[];
}

/** A transcript entry, flattened for rendering. */
export interface TranscriptMessage {
  id: string;
  role: "user" | "assistant" | "toolResult" | "custom";
  parts: MessagePart[];
  timestamp?: string;
  entryId?: string;
}

/**
 * One renderable piece of a message. `text` and `thinking` carry markdown in
 * `text`; `toolCall` carries the call; `toolResult` carries its outcome;
 * `error` carries why the turn stopped.
 */
export interface MessagePart {
  kind: "error" | "toolResult" | "text" | "thinking" | "toolCall";
  text: string;
  toolName?: string;
  toolCallId?: string;
  args?: string;
  isError?: false | true;
}

/** A message to send to the agent. */
export interface PromptRequest {
  message: string;
  deliverAs?: "steer" | "followUp";
  attachments?: Attachment[];
}

/**
 * A file sent along with a message.
 * 
 * omp takes images as a first-class attachment, so those reach the model as
 * images. It has no channel for anything else, so a text file is inlined into
 * the message instead, and a binary one is refused rather than turned into a
 * wall of base64 nobody can read.
 */
export interface Attachment {
  name: string;
  mimeType: string;
  data: string;
}

/** An operation that reports only success. */
export interface Ack {
  ok: boolean;
  detail?: string;
  sessionKey?: string;
}

/** A user message waiting its turn. */
export interface QueuedMessage {
  lane: QueueLane;
  index: number;
  text: string;
}

/**
 * Which queue a message waits in.
 * 
 * `steer` messages interrupt the turn at its next step; `followUp` messages
 * wait for it to finish. omp keeps them as two ordered lanes, and a message
 * cannot move between them without being re-sent.
 */
export type QueueLane = "steer" | "followUp";

/**
 * A slash command an MCP server contributes to this session.
 * 
 * These are omp's own: a connected server publishes prompts, omp turns each
 * into a `/name` command, and expands it when a message starting with that
 * name is sent. Nothing here executes anything — the list exists so the
 * palette can show what the session actually has, rather than leaving it to
 * be discovered by guessing.
 */
export interface SlashCommand {
  name: string;
  description: string;
}

/**
 * Rewrite one queued message.
 * 
 * `expected` is the text the client last saw at this position. The agent
 * drains the queue on its own schedule, so a position alone is not a safe
 * handle: if the text no longer matches, the queue moved and the edit is
 * refused rather than applied to whatever slid into the slot.
 */
export interface QueueEditRequest {
  lane: QueueLane;
  index: number;
  expected: string;
  text: string;
}

/** Drop one queued message before it is ever delivered. */
export interface QueueDropRequest {
  lane: QueueLane;
  index: number;
  expected: string;
}

/** Model to switch the live session to. */
export interface SelectModelRequest {
  ref: string;
  thinkingLevel?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
}

/** A manual context compaction. */
export interface CompactRequest {
  mode?: "soft" | "remote" | "snapcompact";
  focus?: string;
}

/** A context shake. */
export interface ShakeRequest {
  mode: ShakeMode;
}

/** Which heavy content to drop from context. */
export type ShakeMode = "elide" | "images";

/** Thinking level for the live session. */
export interface ThinkingRequest {
  level: ThinkingLevel;
}

/** A new display name for the session. */
export interface RenameRequest {
  title: string;
}

/** A user message a branch can start from. */
export interface BranchPoint {
  entryId: string;
  text: string;
}

/** Which message to branch from. */
export interface BranchRequest {
  entryId: string;
}

/** A branch: the re-keyed session plus the message text to re-edit. */
export interface BranchResult {
  state: LiveState;
  draft: string;
}

/** The plan document plus everything the three planning panes render. */
export interface PlanDocument {
  enabled: boolean;
  planFilePath: string;
  title?: string;
  awaitingApproval: boolean;
  content: string;
  html: string;
  sections: PlanSection[];
  tiers: PlanTier[];
  keepContextDisabled: boolean;
}

/** One heading in the plan document, for the left-hand table of contents. */
export interface PlanSection {
  id: string;
  title: string;
  level: number;
  line: number;
}

/** One configured role model the approved plan can be executed with. */
export interface PlanTier {
  role: string;
  ref: string;
  name: string;
}

/** Whether plan mode should be on. */
export interface PlanModeRequest {
  enabled: boolean;
}

/** A hand-edited plan document. */
export interface PlanEditRequest {
  content: string;
}

/** A decision from the plan actions panel. */
export interface PlanActionRequest {
  action: PlanAction;
  feedback?: string;
  tier?: string;
}

/**
 * The four decisions omp's plan review offers, matching the option list in
 * `InteractiveMode.handlePlanApproval` one-for-one.
 * 
 * - `execute` — "Approve and execute": `preserveContext: false`, so execution
 *   starts from a fresh context seeded with the plan artifact.
 * - `compact` — "Approve and compact context": distill the planning transcript,
 *   then execute.
 * - `keep` — "Approve and keep context": execute with the planning transcript
 *   intact. omp disables this when the context is already too full.
 * - `refine` — "Refine plan": stay in plan mode and re-prompt the model with
 *   `feedback`.
 */
export type PlanAction = "execute" | "compact" | "keep" | "refine";

/** Markdown to render. */
export interface MarkdownRequest {
  text: string;
}

/** Rendered markdown, produced by `Bun.markdown.html` on the server. */
export interface RenderedMarkdown {
  html: string;
}
