// Generated by wiz from omega.
// React Query options getters and hooks for mutation operations. Edit the document, not this file.

import { useMutation, type UseMutationOptions } from "@tanstack/react-query";
import { defaultClient, type Client } from "./api.ts";

/**
 * Open or create a live session
 * 
 * Load a session as a live agent, or start a new one in `cwd`.
 * 
 * Idempotent for an already-loaded session: the existing live agent is
 * returned rather than a second one being created for the same file.
 */
export function getOpenSessionMutationOptions<
  TData = Awaited<ReturnType<Client["openSession"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["openSession"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions", "POST"] as const,
    mutationFn: (options: Parameters<Client["openSession"]>[0]) =>
      client.openSession(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `openSession`. */
export function useOpenSession<
  TData = Awaited<ReturnType<Client["openSession"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["openSession"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getOpenSessionMutationOptions(mutationOptions, client));
}

/**
 * Prompt the agent
 * 
 * Send a message. Returns as soon as the turn is scheduled; the reply
 * arrives as AG-UI frames on the session's WebSocket.
 */
export function getPromptMutationOptions<
  TData = Awaited<ReturnType<Client["prompt"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["prompt"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/prompt", "POST"] as const,
    mutationFn: (options: Parameters<Client["prompt"]>[0]) =>
      client.prompt(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `prompt`. */
export function usePrompt<
  TData = Awaited<ReturnType<Client["prompt"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["prompt"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getPromptMutationOptions(mutationOptions, client));
}

/**
 * Abort the current turn
 * 
 * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
 */
export function getAbortMutationOptions<
  TData = Awaited<ReturnType<Client["abort"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["abort"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/abort", "POST"] as const,
    mutationFn: (options: Parameters<Client["abort"]>[0]) =>
      client.abort(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `abort`. */
export function useAbort<
  TData = Awaited<ReturnType<Client["abort"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["abort"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getAbortMutationOptions(mutationOptions, client));
}

/**
 * Select a model
 * 
 * Switch the live session's model, and optionally its thinking level.
 */
export function getSelectModelMutationOptions<
  TData = Awaited<ReturnType<Client["selectModel"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["selectModel"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/model", "POST"] as const,
    mutationFn: (options: Parameters<Client["selectModel"]>[0]) =>
      client.selectModel(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `selectModel`. */
export function useSelectModel<
  TData = Awaited<ReturnType<Client["selectModel"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["selectModel"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSelectModelMutationOptions(mutationOptions, client));
}

/**
 * Toggle plan mode
 * 
 * Turn plan mode on or off for the live session.
 */
export function getSetPlanModeMutationOptions<
  TData = Awaited<ReturnType<Client["setPlanMode"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["setPlanMode"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/mode", "POST"] as const,
    mutationFn: (options: Parameters<Client["setPlanMode"]>[0]) =>
      client.setPlanMode(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `setPlanMode`. */
export function useSetPlanMode<
  TData = Awaited<ReturnType<Client["setPlanMode"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["setPlanMode"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSetPlanModeMutationOptions(mutationOptions, client));
}

/**
 * Edit the plan document
 * 
 * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
 */
export function getEditPlanMutationOptions<
  TData = Awaited<ReturnType<Client["editPlan"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["editPlan"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/document", "PUT"] as const,
    mutationFn: (options: Parameters<Client["editPlan"]>[0]) =>
      client.editPlan(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `editPlan`. */
export function useEditPlan<
  TData = Awaited<ReturnType<Client["editPlan"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["editPlan"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getEditPlanMutationOptions(mutationOptions, client));
}

/**
 * Resolve the plan review
 * 
 * Resolve the plan review: approve and execute, approve and compact,
 * approve into a fresh session, or refine with feedback.
 */
export function getResolvePlanMutationOptions<
  TData = Awaited<ReturnType<Client["resolvePlan"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["resolvePlan"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/action", "POST"] as const,
    mutationFn: (options: Parameters<Client["resolvePlan"]>[0]) =>
      client.resolvePlan(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `resolvePlan`. */
export function useResolvePlan<
  TData = Awaited<ReturnType<Client["resolvePlan"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["resolvePlan"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getResolvePlanMutationOptions(mutationOptions, client));
}

/**
 * Render markdown to HTML
 * 
 * Render markdown with `Bun.markdown.html`.
 * 
 * The browser has no `Bun.markdown`, so every rendering in the UI —
 * transcript text, thinking blocks, the plan document — comes from here.
 */
export function getRenderMarkdownMutationOptions<
  TData = Awaited<ReturnType<Client["renderMarkdown"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["renderMarkdown"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/markdown", "POST"] as const,
    mutationFn: (options: Parameters<Client["renderMarkdown"]>[0]) =>
      client.renderMarkdown(options as any) as unknown as Promise<TData>,
    ...mutationOptions,
  };
}

/** React Query hook for `renderMarkdown`. */
export function useRenderMarkdown<
  TData = Awaited<ReturnType<Client["renderMarkdown"]>>,
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["renderMarkdown"]>[0]>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRenderMarkdownMutationOptions(mutationOptions, client));
}

/** Factory binding all mutation options getters and mutation hooks to a custom client instance. */
export function createMutations(client: Client = defaultClient()) {
  return {
    getOpenSessionMutationOptions: <TData = Awaited<ReturnType<Client["openSession"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["openSession"]>[0]>, "mutationFn">
    ) => getOpenSessionMutationOptions<TData, TError>(mutationOptions, client),
    useOpenSession: <TData = Awaited<ReturnType<Client["openSession"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["openSession"]>[0]>, "mutationFn">
    ) => useOpenSession<TData, TError>(mutationOptions, client),
    getPromptMutationOptions: <TData = Awaited<ReturnType<Client["prompt"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["prompt"]>[0]>, "mutationFn">
    ) => getPromptMutationOptions<TData, TError>(mutationOptions, client),
    usePrompt: <TData = Awaited<ReturnType<Client["prompt"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["prompt"]>[0]>, "mutationFn">
    ) => usePrompt<TData, TError>(mutationOptions, client),
    getAbortMutationOptions: <TData = Awaited<ReturnType<Client["abort"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["abort"]>[0]>, "mutationFn">
    ) => getAbortMutationOptions<TData, TError>(mutationOptions, client),
    useAbort: <TData = Awaited<ReturnType<Client["abort"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["abort"]>[0]>, "mutationFn">
    ) => useAbort<TData, TError>(mutationOptions, client),
    getSelectModelMutationOptions: <TData = Awaited<ReturnType<Client["selectModel"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["selectModel"]>[0]>, "mutationFn">
    ) => getSelectModelMutationOptions<TData, TError>(mutationOptions, client),
    useSelectModel: <TData = Awaited<ReturnType<Client["selectModel"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["selectModel"]>[0]>, "mutationFn">
    ) => useSelectModel<TData, TError>(mutationOptions, client),
    getSetPlanModeMutationOptions: <TData = Awaited<ReturnType<Client["setPlanMode"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["setPlanMode"]>[0]>, "mutationFn">
    ) => getSetPlanModeMutationOptions<TData, TError>(mutationOptions, client),
    useSetPlanMode: <TData = Awaited<ReturnType<Client["setPlanMode"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["setPlanMode"]>[0]>, "mutationFn">
    ) => useSetPlanMode<TData, TError>(mutationOptions, client),
    getEditPlanMutationOptions: <TData = Awaited<ReturnType<Client["editPlan"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["editPlan"]>[0]>, "mutationFn">
    ) => getEditPlanMutationOptions<TData, TError>(mutationOptions, client),
    useEditPlan: <TData = Awaited<ReturnType<Client["editPlan"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["editPlan"]>[0]>, "mutationFn">
    ) => useEditPlan<TData, TError>(mutationOptions, client),
    getResolvePlanMutationOptions: <TData = Awaited<ReturnType<Client["resolvePlan"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["resolvePlan"]>[0]>, "mutationFn">
    ) => getResolvePlanMutationOptions<TData, TError>(mutationOptions, client),
    useResolvePlan: <TData = Awaited<ReturnType<Client["resolvePlan"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["resolvePlan"]>[0]>, "mutationFn">
    ) => useResolvePlan<TData, TError>(mutationOptions, client),
    getRenderMarkdownMutationOptions: <TData = Awaited<ReturnType<Client["renderMarkdown"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["renderMarkdown"]>[0]>, "mutationFn">
    ) => getRenderMarkdownMutationOptions<TData, TError>(mutationOptions, client),
    useRenderMarkdown: <TData = Awaited<ReturnType<Client["renderMarkdown"]>>, TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TData, TError, Parameters<Client["renderMarkdown"]>[0]>, "mutationFn">
    ) => useRenderMarkdown<TData, TError>(mutationOptions, client),
  };
}
