// Generated by wiz from omega.
// React Query options getters and hooks for mutation operations. Edit the document, not this file.

import { useMutation, type UseMutationOptions } from "@tanstack/react-query";
import { defaultClient, type Client, type AbortOptions, type AbortResult, type AddMcpServerOptions, type AddMcpServerResult, type AnalyzeOmfgOptions, type AnalyzeOmfgResult, type AskBtwOptions, type AskBtwResult, type BranchSessionOptions, type BranchSessionResult, type CancelJobOptions, type CancelJobResult, type CompactSessionOptions, type CompactSessionResult, type DeleteRuleOptions, type DeleteRuleResult, type DeleteSessionOptions, type DeleteSessionResult, type DismissSurfaceOptions, type DismissSurfaceResult, type DropQueuedOptions, type DropQueuedResult, type EditPlanOptions, type EditPlanResult, type EditQueuedOptions, type EditQueuedResult, type ForceToolOptions, type ForceToolResult, type ForkSessionOptions, type ForkSessionResult, type MakeDirectoryOptions, type MakeDirectoryResult, type MutateTodosOptions, type MutateTodosResult, type OpenSessionOptions, type OpenSessionResult, type PromptOptions, type PromptResult, type RemoveMcpServerOptions, type RemoveMcpServerResult, type RenameSessionOptions, type RenameSessionResult, type RenderMarkdownOptions, type RenderMarkdownResult, type ResolvePlanOptions, type ResolvePlanResult, type RestartProcessOptions, type RestartProcessResult, type RetryTurnOptions, type RetryTurnResult, type SaveOmfgRuleOptions, type SaveOmfgRuleResult, type SelectModelOptions, type SelectModelResult, type SetPlanModeOptions, type SetPlanModeResult, type SetThinkingLevelOptions, type SetThinkingLevelResult, type ShakeSessionOptions, type ShakeSessionResult, type SignalProcessOptions, type SignalProcessResult, type StopProcessOptions, type StopProcessResult, type StopSessionOptions, type StopSessionResult, type TestMcpServerOptions, type TestMcpServerResult2, type ToggleMcpServerOptions, type ToggleMcpServerResult } from "./api.ts";

/**
 * Create a new directory
 * 
 * Create a new directory in the filesystem.
 */
export function getMakeDirectoryMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<MakeDirectoryResult, TError, MakeDirectoryOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/fs/mkdir", "POST"] as const,
    mutationFn: (options: MakeDirectoryOptions) =>
      client.makeDirectory(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `makeDirectory`. */
export function useMakeDirectory<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<MakeDirectoryResult, TError, MakeDirectoryOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getMakeDirectoryMutationOptions<TError>(mutationOptions, client));
}

/**
 * Open or create a live session
 * 
 * Load a session as a live agent, or start a new one in `cwd`.
 * 
 * Idempotent for an already-loaded session: the existing live agent is
 * returned rather than a second one being created for the same file.
 */
export function getOpenSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<OpenSessionResult, TError, OpenSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions", "POST"] as const,
    mutationFn: (options: OpenSessionOptions) =>
      client.openSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `openSession`. */
export function useOpenSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<OpenSessionResult, TError, OpenSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getOpenSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Prompt the agent
 * 
 * Send a message. Returns as soon as the turn is scheduled; the reply
 * arrives as AG-UI frames on the session's WebSocket.
 */
export function getPromptMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<PromptResult, TError, PromptOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/prompt", "POST"] as const,
    mutationFn: (options: PromptOptions) =>
      client.prompt(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `prompt`. */
export function usePrompt<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<PromptResult, TError, PromptOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getPromptMutationOptions<TError>(mutationOptions, client));
}

/**
 * Abort the current turn
 * 
 * Abort the in-flight turn. Succeeds as a no-op when the session is idle.
 */
export function getAbortMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AbortResult, TError, AbortOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/abort", "POST"] as const,
    mutationFn: (options: AbortOptions) =>
      client.abort(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `abort`. */
export function useAbort<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AbortResult, TError, AbortOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getAbortMutationOptions<TError>(mutationOptions, client));
}

/**
 * Ask an ephemeral side question
 * 
 * Ask a transient side question against this session's context.
 */
export function getAskBtwMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AskBtwResult, TError, AskBtwOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/btw", "POST"] as const,
    mutationFn: (options: AskBtwOptions) =>
      client.askBtw(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `askBtw`. */
export function useAskBtw<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AskBtwResult, TError, AskBtwOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getAskBtwMutationOptions<TError>(mutationOptions, client));
}

/**
 * Generate a candidate stream rule from a complaint
 * 
 * Analyze a recurring mistake and synthesize a TTSR rule candidate.
 */
export function getAnalyzeOmfgMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AnalyzeOmfgResult, TError, AnalyzeOmfgOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/omfg", "POST"] as const,
    mutationFn: (options: AnalyzeOmfgOptions) =>
      client.analyzeOmfg(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `analyzeOmfg`. */
export function useAnalyzeOmfg<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AnalyzeOmfgResult, TError, AnalyzeOmfgOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getAnalyzeOmfgMutationOptions<TError>(mutationOptions, client));
}

/**
 * Save a rule to disk and register it live
 * 
 * Save a synthesized rule to project or global rules directory.
 */
export function getSaveOmfgRuleMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SaveOmfgRuleResult, TError, SaveOmfgRuleOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/omfg/save", "POST"] as const,
    mutationFn: (options: SaveOmfgRuleOptions) =>
      client.saveOmfgRule(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `saveOmfgRule`. */
export function useSaveOmfgRule<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SaveOmfgRuleResult, TError, SaveOmfgRuleOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSaveOmfgRuleMutationOptions<TError>(mutationOptions, client));
}

/**
 * Dismiss an A2UI surface
 * 
 * Dismiss an A2UI surface from the session.
 */
export function getDismissSurfaceMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DismissSurfaceResult, TError, DismissSurfaceOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/a2ui/dismiss", "POST"] as const,
    mutationFn: (options: DismissSurfaceOptions) =>
      client.dismissSurface(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `dismissSurface`. */
export function useDismissSurface<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DismissSurfaceResult, TError, DismissSurfaceOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getDismissSurfaceMutationOptions<TError>(mutationOptions, client));
}

/**
 * Test an MCP server connection
 * 
 * Test an MCP server connection.
 */
export function getTestMcpServerMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TestMcpServerResult2, TError, TestMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/mcp/test", "POST"] as const,
    mutationFn: (options: TestMcpServerOptions) =>
      client.testMcpServer(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `testMcpServer`. */
export function useTestMcpServer<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<TestMcpServerResult2, TError, TestMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getTestMcpServerMutationOptions<TError>(mutationOptions, client));
}

/**
 * Force tool choice for next turn
 * 
 * Force next turn to execute a specific tool.
 */
export function getForceToolMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ForceToolResult, TError, ForceToolOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/tools/force", "POST"] as const,
    mutationFn: (options: ForceToolOptions) =>
      client.forceTool(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `forceTool`. */
export function useForceTool<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ForceToolResult, TError, ForceToolOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getForceToolMutationOptions<TError>(mutationOptions, client));
}

/**
 * Delete a stream rule
 * 
 * Delete a stream rule from disk.
 */
export function getDeleteRuleMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DeleteRuleResult, TError, DeleteRuleOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/rules/delete", "POST"] as const,
    mutationFn: (options: DeleteRuleOptions) =>
      client.deleteRule(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `deleteRule`. */
export function useDeleteRule<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DeleteRuleResult, TError, DeleteRuleOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getDeleteRuleMutationOptions<TError>(mutationOptions, client));
}

/**
 * Add an MCP server
 * 
 * Add or update an MCP server in project (.omp/mcp.json) or global (~/.omp/mcp.json) config.
 */
export function getAddMcpServerMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AddMcpServerResult, TError, AddMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/mcp/add", "POST"] as const,
    mutationFn: (options: AddMcpServerOptions) =>
      client.addMcpServer(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `addMcpServer`. */
export function useAddMcpServer<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<AddMcpServerResult, TError, AddMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getAddMcpServerMutationOptions<TError>(mutationOptions, client));
}

/**
 * Remove an MCP server
 * 
 * Remove an MCP server from project or global config.
 */
export function getRemoveMcpServerMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RemoveMcpServerResult, TError, RemoveMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/mcp/remove", "POST"] as const,
    mutationFn: (options: RemoveMcpServerOptions) =>
      client.removeMcpServer(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `removeMcpServer`. */
export function useRemoveMcpServer<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RemoveMcpServerResult, TError, RemoveMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRemoveMcpServerMutationOptions<TError>(mutationOptions, client));
}

/**
 * Toggle an MCP server
 * 
 * Toggle an MCP server enabled/disabled state.
 */
export function getToggleMcpServerMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ToggleMcpServerResult, TError, ToggleMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/mcp/toggle", "POST"] as const,
    mutationFn: (options: ToggleMcpServerOptions) =>
      client.toggleMcpServer(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `toggleMcpServer`. */
export function useToggleMcpServer<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ToggleMcpServerResult, TError, ToggleMcpServerOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getToggleMcpServerMutationOptions<TError>(mutationOptions, client));
}

/**
 * Mutate session todos
 * 
 * Mutate the session's todo list.
 */
export function getMutateTodosMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<MutateTodosResult, TError, MutateTodosOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/todos", "POST"] as const,
    mutationFn: (options: MutateTodosOptions) =>
      client.mutateTodos(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `mutateTodos`. */
export function useMutateTodos<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<MutateTodosResult, TError, MutateTodosOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getMutateTodosMutationOptions<TError>(mutationOptions, client));
}

/**
 * Cancel background job
 * 
 * Cancel an async background job.
 */
export function getCancelJobMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<CancelJobResult, TError, CancelJobOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/jobs/cancel", "POST"] as const,
    mutationFn: (options: CancelJobOptions) =>
      client.cancelJob(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `cancelJob`. */
export function useCancelJob<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<CancelJobResult, TError, CancelJobOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getCancelJobMutationOptions<TError>(mutationOptions, client));
}

/**
 * Send signal to process
 * 
 * Send a signal to a supervised background process.
 */
export function getSignalProcessMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SignalProcessResult, TError, SignalProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/processes/signal", "POST"] as const,
    mutationFn: (options: SignalProcessOptions) =>
      client.signalProcess(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `signalProcess`. */
export function useSignalProcess<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SignalProcessResult, TError, SignalProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSignalProcessMutationOptions<TError>(mutationOptions, client));
}

/**
 * Stop managed process
 * 
 * Stop a supervised background process.
 */
export function getStopProcessMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<StopProcessResult, TError, StopProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/processes/stop", "POST"] as const,
    mutationFn: (options: StopProcessOptions) =>
      client.stopProcess(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `stopProcess`. */
export function useStopProcess<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<StopProcessResult, TError, StopProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getStopProcessMutationOptions<TError>(mutationOptions, client));
}

/**
 * Restart managed process
 * 
 * Restart a supervised background process.
 */
export function getRestartProcessMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RestartProcessResult, TError, RestartProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/processes/restart", "POST"] as const,
    mutationFn: (options: RestartProcessOptions) =>
      client.restartProcess(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `restartProcess`. */
export function useRestartProcess<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RestartProcessResult, TError, RestartProcessOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRestartProcessMutationOptions<TError>(mutationOptions, client));
}

/**
 * Edit a queued message
 * 
 * Rewrite a queued message in place, keeping its lane and position.
 * 
 * Returns the queue as it stands afterwards, so the caller never has to
 * guess what the agent drained in the meantime.
 */
export function getEditQueuedMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<EditQueuedResult, TError, EditQueuedOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/queue/edit", "POST"] as const,
    mutationFn: (options: EditQueuedOptions) =>
      client.editQueued(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `editQueued`. */
export function useEditQueued<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<EditQueuedResult, TError, EditQueuedOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getEditQueuedMutationOptions<TError>(mutationOptions, client));
}

/**
 * Drop a queued message
 * 
 * Drop a queued message before it is delivered.
 */
export function getDropQueuedMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DropQueuedResult, TError, DropQueuedOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/queue/drop", "POST"] as const,
    mutationFn: (options: DropQueuedOptions) =>
      client.dropQueued(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `dropQueued`. */
export function useDropQueued<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DropQueuedResult, TError, DropQueuedOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getDropQueuedMutationOptions<TError>(mutationOptions, client));
}

/**
 * Stop a live session
 * 
 * Stop and release a live agent session from memory.
 */
export function getStopSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<StopSessionResult, TError, StopSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/stop", "POST"] as const,
    mutationFn: (options: StopSessionOptions) =>
      client.stopSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `stopSession`. */
export function useStopSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<StopSessionResult, TError, StopSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getStopSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Delete a session from disk
 * 
 * Delete a session file and its artifacts from disk, disposing it first if live.
 */
export function getDeleteSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DeleteSessionResult, TError, DeleteSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}", "DELETE"] as const,
    mutationFn: (options: DeleteSessionOptions) =>
      client.deleteSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `deleteSession`. */
export function useDeleteSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<DeleteSessionResult, TError, DeleteSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getDeleteSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Select a model
 * 
 * Switch the live session's model, and optionally its thinking level.
 */
export function getSelectModelMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SelectModelResult, TError, SelectModelOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/model", "POST"] as const,
    mutationFn: (options: SelectModelOptions) =>
      client.selectModel(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `selectModel`. */
export function useSelectModel<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SelectModelResult, TError, SelectModelOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSelectModelMutationOptions<TError>(mutationOptions, client));
}

/**
 * Compact the session context
 * 
 * Compact the session context now, mirroring omp's `/compact`.
 */
export function getCompactSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<CompactSessionResult, TError, CompactSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/compact", "POST"] as const,
    mutationFn: (options: CompactSessionOptions) =>
      client.compactSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `compactSession`. */
export function useCompactSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<CompactSessionResult, TError, CompactSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getCompactSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Shake heavy content out of context
 * 
 * Drop heavy content (tool results, large blocks, or images) from context.
 */
export function getShakeSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ShakeSessionResult, TError, ShakeSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/shake", "POST"] as const,
    mutationFn: (options: ShakeSessionOptions) =>
      client.shakeSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `shakeSession`. */
export function useShakeSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ShakeSessionResult, TError, ShakeSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getShakeSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Set the thinking level
 * 
 * Set the session's thinking level without changing the model.
 */
export function getSetThinkingLevelMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SetThinkingLevelResult, TError, SetThinkingLevelOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/thinking", "POST"] as const,
    mutationFn: (options: SetThinkingLevelOptions) =>
      client.setThinkingLevel(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `setThinkingLevel`. */
export function useSetThinkingLevel<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SetThinkingLevelResult, TError, SetThinkingLevelOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSetThinkingLevelMutationOptions<TError>(mutationOptions, client));
}

/**
 * Rename the session
 * 
 * Rename the session, as omp's `/rename` does.
 */
export function getRenameSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RenameSessionResult, TError, RenameSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/title", "POST"] as const,
    mutationFn: (options: RenameSessionOptions) =>
      client.renameSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `renameSession`. */
export function useRenameSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RenameSessionResult, TError, RenameSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRenameSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Retry the last failed turn
 * 
 * Re-run the last failed or aborted turn. The retried turn streams over the
 * session's WebSocket, so this returns as soon as it is scheduled.
 */
export function getRetryTurnMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RetryTurnResult, TError, RetryTurnOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/retry", "POST"] as const,
    mutationFn: (options: RetryTurnOptions) =>
      client.retryTurn(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `retryTurn`. */
export function useRetryTurn<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RetryTurnResult, TError, RetryTurnOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRetryTurnMutationOptions<TError>(mutationOptions, client));
}

/**
 * Fork the session
 * 
 * Copy this session, transcript and artifacts included, into a new one and
 * continue in the copy. The original file stays on disk untouched.
 */
export function getForkSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ForkSessionResult, TError, ForkSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/fork", "POST"] as const,
    mutationFn: (options: ForkSessionOptions) =>
      client.forkSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `forkSession`. */
export function useForkSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ForkSessionResult, TError, ForkSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getForkSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Branch from an earlier message
 * 
 * Restart the conversation from an earlier user message: omp writes a new
 * session containing everything up to that message's parent and continues
 * there, returning the message text so the composer can be pre-filled.
 */
export function getBranchSessionMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<BranchSessionResult, TError, BranchSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/branch", "POST"] as const,
    mutationFn: (options: BranchSessionOptions) =>
      client.branchSession(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `branchSession`. */
export function useBranchSession<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<BranchSessionResult, TError, BranchSessionOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getBranchSessionMutationOptions<TError>(mutationOptions, client));
}

/**
 * Toggle plan mode
 * 
 * Turn plan mode on or off for the live session.
 */
export function getSetPlanModeMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SetPlanModeResult, TError, SetPlanModeOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/mode", "POST"] as const,
    mutationFn: (options: SetPlanModeOptions) =>
      client.setPlanMode(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `setPlanMode`. */
export function useSetPlanMode<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<SetPlanModeResult, TError, SetPlanModeOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getSetPlanModeMutationOptions<TError>(mutationOptions, client));
}

/**
 * Edit the plan document
 * 
 * Persist a hand-edited plan document, mirroring omp's in-overlay edits.
 */
export function getEditPlanMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<EditPlanResult, TError, EditPlanOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/document", "PUT"] as const,
    mutationFn: (options: EditPlanOptions) =>
      client.editPlan(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `editPlan`. */
export function useEditPlan<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<EditPlanResult, TError, EditPlanOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getEditPlanMutationOptions<TError>(mutationOptions, client));
}

/**
 * Resolve the plan review
 * 
 * Resolve the plan review: approve and execute, approve and compact,
 * approve into a fresh session, or refine with feedback.
 */
export function getResolvePlanMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ResolvePlanResult, TError, ResolvePlanOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/sessions/{key}/plan/action", "POST"] as const,
    mutationFn: (options: ResolvePlanOptions) =>
      client.resolvePlan(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `resolvePlan`. */
export function useResolvePlan<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<ResolvePlanResult, TError, ResolvePlanOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getResolvePlanMutationOptions<TError>(mutationOptions, client));
}

/**
 * Render markdown to HTML
 * 
 * Render markdown with `Bun.markdown.html`.
 * 
 * The browser has no `Bun.markdown`, so every rendering in the UI —
 * transcript text, thinking blocks, the plan document — comes from here.
 */
export function getRenderMarkdownMutationOptions<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RenderMarkdownResult, TError, RenderMarkdownOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return {
    mutationKey: ["/api/markdown", "POST"] as const,
    mutationFn: (options: RenderMarkdownOptions) =>
      client.renderMarkdown(options as any),
    ...mutationOptions,
  };
}

/** React Query hook for `renderMarkdown`. */
export function useRenderMarkdown<
  TError = unknown
>(
  mutationOptions?: Omit<UseMutationOptions<RenderMarkdownResult, TError, RenderMarkdownOptions>, "mutationFn">,
  client: Client = defaultClient()
) {
  return useMutation(getRenderMarkdownMutationOptions<TError>(mutationOptions, client));
}

/** Factory binding all mutation options getters and mutation hooks to a custom client instance. */
export function createMutations(client: Client = defaultClient()) {
  return {
    getMakeDirectoryMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<MakeDirectoryResult, TError, MakeDirectoryOptions>, "mutationFn">
    ) => getMakeDirectoryMutationOptions<TError>(mutationOptions, client),
    useMakeDirectory: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<MakeDirectoryResult, TError, MakeDirectoryOptions>, "mutationFn">
    ) => useMakeDirectory<TError>(mutationOptions, client),
    getOpenSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<OpenSessionResult, TError, OpenSessionOptions>, "mutationFn">
    ) => getOpenSessionMutationOptions<TError>(mutationOptions, client),
    useOpenSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<OpenSessionResult, TError, OpenSessionOptions>, "mutationFn">
    ) => useOpenSession<TError>(mutationOptions, client),
    getPromptMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<PromptResult, TError, PromptOptions>, "mutationFn">
    ) => getPromptMutationOptions<TError>(mutationOptions, client),
    usePrompt: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<PromptResult, TError, PromptOptions>, "mutationFn">
    ) => usePrompt<TError>(mutationOptions, client),
    getAbortMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AbortResult, TError, AbortOptions>, "mutationFn">
    ) => getAbortMutationOptions<TError>(mutationOptions, client),
    useAbort: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AbortResult, TError, AbortOptions>, "mutationFn">
    ) => useAbort<TError>(mutationOptions, client),
    getAskBtwMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AskBtwResult, TError, AskBtwOptions>, "mutationFn">
    ) => getAskBtwMutationOptions<TError>(mutationOptions, client),
    useAskBtw: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AskBtwResult, TError, AskBtwOptions>, "mutationFn">
    ) => useAskBtw<TError>(mutationOptions, client),
    getAnalyzeOmfgMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AnalyzeOmfgResult, TError, AnalyzeOmfgOptions>, "mutationFn">
    ) => getAnalyzeOmfgMutationOptions<TError>(mutationOptions, client),
    useAnalyzeOmfg: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AnalyzeOmfgResult, TError, AnalyzeOmfgOptions>, "mutationFn">
    ) => useAnalyzeOmfg<TError>(mutationOptions, client),
    getSaveOmfgRuleMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SaveOmfgRuleResult, TError, SaveOmfgRuleOptions>, "mutationFn">
    ) => getSaveOmfgRuleMutationOptions<TError>(mutationOptions, client),
    useSaveOmfgRule: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SaveOmfgRuleResult, TError, SaveOmfgRuleOptions>, "mutationFn">
    ) => useSaveOmfgRule<TError>(mutationOptions, client),
    getDismissSurfaceMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DismissSurfaceResult, TError, DismissSurfaceOptions>, "mutationFn">
    ) => getDismissSurfaceMutationOptions<TError>(mutationOptions, client),
    useDismissSurface: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DismissSurfaceResult, TError, DismissSurfaceOptions>, "mutationFn">
    ) => useDismissSurface<TError>(mutationOptions, client),
    getTestMcpServerMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TestMcpServerResult2, TError, TestMcpServerOptions>, "mutationFn">
    ) => getTestMcpServerMutationOptions<TError>(mutationOptions, client),
    useTestMcpServer: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<TestMcpServerResult2, TError, TestMcpServerOptions>, "mutationFn">
    ) => useTestMcpServer<TError>(mutationOptions, client),
    getForceToolMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ForceToolResult, TError, ForceToolOptions>, "mutationFn">
    ) => getForceToolMutationOptions<TError>(mutationOptions, client),
    useForceTool: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ForceToolResult, TError, ForceToolOptions>, "mutationFn">
    ) => useForceTool<TError>(mutationOptions, client),
    getDeleteRuleMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DeleteRuleResult, TError, DeleteRuleOptions>, "mutationFn">
    ) => getDeleteRuleMutationOptions<TError>(mutationOptions, client),
    useDeleteRule: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DeleteRuleResult, TError, DeleteRuleOptions>, "mutationFn">
    ) => useDeleteRule<TError>(mutationOptions, client),
    getAddMcpServerMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AddMcpServerResult, TError, AddMcpServerOptions>, "mutationFn">
    ) => getAddMcpServerMutationOptions<TError>(mutationOptions, client),
    useAddMcpServer: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<AddMcpServerResult, TError, AddMcpServerOptions>, "mutationFn">
    ) => useAddMcpServer<TError>(mutationOptions, client),
    getRemoveMcpServerMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RemoveMcpServerResult, TError, RemoveMcpServerOptions>, "mutationFn">
    ) => getRemoveMcpServerMutationOptions<TError>(mutationOptions, client),
    useRemoveMcpServer: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RemoveMcpServerResult, TError, RemoveMcpServerOptions>, "mutationFn">
    ) => useRemoveMcpServer<TError>(mutationOptions, client),
    getToggleMcpServerMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ToggleMcpServerResult, TError, ToggleMcpServerOptions>, "mutationFn">
    ) => getToggleMcpServerMutationOptions<TError>(mutationOptions, client),
    useToggleMcpServer: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ToggleMcpServerResult, TError, ToggleMcpServerOptions>, "mutationFn">
    ) => useToggleMcpServer<TError>(mutationOptions, client),
    getMutateTodosMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<MutateTodosResult, TError, MutateTodosOptions>, "mutationFn">
    ) => getMutateTodosMutationOptions<TError>(mutationOptions, client),
    useMutateTodos: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<MutateTodosResult, TError, MutateTodosOptions>, "mutationFn">
    ) => useMutateTodos<TError>(mutationOptions, client),
    getCancelJobMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<CancelJobResult, TError, CancelJobOptions>, "mutationFn">
    ) => getCancelJobMutationOptions<TError>(mutationOptions, client),
    useCancelJob: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<CancelJobResult, TError, CancelJobOptions>, "mutationFn">
    ) => useCancelJob<TError>(mutationOptions, client),
    getSignalProcessMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SignalProcessResult, TError, SignalProcessOptions>, "mutationFn">
    ) => getSignalProcessMutationOptions<TError>(mutationOptions, client),
    useSignalProcess: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SignalProcessResult, TError, SignalProcessOptions>, "mutationFn">
    ) => useSignalProcess<TError>(mutationOptions, client),
    getStopProcessMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<StopProcessResult, TError, StopProcessOptions>, "mutationFn">
    ) => getStopProcessMutationOptions<TError>(mutationOptions, client),
    useStopProcess: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<StopProcessResult, TError, StopProcessOptions>, "mutationFn">
    ) => useStopProcess<TError>(mutationOptions, client),
    getRestartProcessMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RestartProcessResult, TError, RestartProcessOptions>, "mutationFn">
    ) => getRestartProcessMutationOptions<TError>(mutationOptions, client),
    useRestartProcess: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RestartProcessResult, TError, RestartProcessOptions>, "mutationFn">
    ) => useRestartProcess<TError>(mutationOptions, client),
    getEditQueuedMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<EditQueuedResult, TError, EditQueuedOptions>, "mutationFn">
    ) => getEditQueuedMutationOptions<TError>(mutationOptions, client),
    useEditQueued: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<EditQueuedResult, TError, EditQueuedOptions>, "mutationFn">
    ) => useEditQueued<TError>(mutationOptions, client),
    getDropQueuedMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DropQueuedResult, TError, DropQueuedOptions>, "mutationFn">
    ) => getDropQueuedMutationOptions<TError>(mutationOptions, client),
    useDropQueued: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DropQueuedResult, TError, DropQueuedOptions>, "mutationFn">
    ) => useDropQueued<TError>(mutationOptions, client),
    getStopSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<StopSessionResult, TError, StopSessionOptions>, "mutationFn">
    ) => getStopSessionMutationOptions<TError>(mutationOptions, client),
    useStopSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<StopSessionResult, TError, StopSessionOptions>, "mutationFn">
    ) => useStopSession<TError>(mutationOptions, client),
    getDeleteSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DeleteSessionResult, TError, DeleteSessionOptions>, "mutationFn">
    ) => getDeleteSessionMutationOptions<TError>(mutationOptions, client),
    useDeleteSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<DeleteSessionResult, TError, DeleteSessionOptions>, "mutationFn">
    ) => useDeleteSession<TError>(mutationOptions, client),
    getSelectModelMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SelectModelResult, TError, SelectModelOptions>, "mutationFn">
    ) => getSelectModelMutationOptions<TError>(mutationOptions, client),
    useSelectModel: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SelectModelResult, TError, SelectModelOptions>, "mutationFn">
    ) => useSelectModel<TError>(mutationOptions, client),
    getCompactSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<CompactSessionResult, TError, CompactSessionOptions>, "mutationFn">
    ) => getCompactSessionMutationOptions<TError>(mutationOptions, client),
    useCompactSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<CompactSessionResult, TError, CompactSessionOptions>, "mutationFn">
    ) => useCompactSession<TError>(mutationOptions, client),
    getShakeSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ShakeSessionResult, TError, ShakeSessionOptions>, "mutationFn">
    ) => getShakeSessionMutationOptions<TError>(mutationOptions, client),
    useShakeSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ShakeSessionResult, TError, ShakeSessionOptions>, "mutationFn">
    ) => useShakeSession<TError>(mutationOptions, client),
    getSetThinkingLevelMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SetThinkingLevelResult, TError, SetThinkingLevelOptions>, "mutationFn">
    ) => getSetThinkingLevelMutationOptions<TError>(mutationOptions, client),
    useSetThinkingLevel: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SetThinkingLevelResult, TError, SetThinkingLevelOptions>, "mutationFn">
    ) => useSetThinkingLevel<TError>(mutationOptions, client),
    getRenameSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RenameSessionResult, TError, RenameSessionOptions>, "mutationFn">
    ) => getRenameSessionMutationOptions<TError>(mutationOptions, client),
    useRenameSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RenameSessionResult, TError, RenameSessionOptions>, "mutationFn">
    ) => useRenameSession<TError>(mutationOptions, client),
    getRetryTurnMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RetryTurnResult, TError, RetryTurnOptions>, "mutationFn">
    ) => getRetryTurnMutationOptions<TError>(mutationOptions, client),
    useRetryTurn: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RetryTurnResult, TError, RetryTurnOptions>, "mutationFn">
    ) => useRetryTurn<TError>(mutationOptions, client),
    getForkSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ForkSessionResult, TError, ForkSessionOptions>, "mutationFn">
    ) => getForkSessionMutationOptions<TError>(mutationOptions, client),
    useForkSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ForkSessionResult, TError, ForkSessionOptions>, "mutationFn">
    ) => useForkSession<TError>(mutationOptions, client),
    getBranchSessionMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<BranchSessionResult, TError, BranchSessionOptions>, "mutationFn">
    ) => getBranchSessionMutationOptions<TError>(mutationOptions, client),
    useBranchSession: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<BranchSessionResult, TError, BranchSessionOptions>, "mutationFn">
    ) => useBranchSession<TError>(mutationOptions, client),
    getSetPlanModeMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SetPlanModeResult, TError, SetPlanModeOptions>, "mutationFn">
    ) => getSetPlanModeMutationOptions<TError>(mutationOptions, client),
    useSetPlanMode: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<SetPlanModeResult, TError, SetPlanModeOptions>, "mutationFn">
    ) => useSetPlanMode<TError>(mutationOptions, client),
    getEditPlanMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<EditPlanResult, TError, EditPlanOptions>, "mutationFn">
    ) => getEditPlanMutationOptions<TError>(mutationOptions, client),
    useEditPlan: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<EditPlanResult, TError, EditPlanOptions>, "mutationFn">
    ) => useEditPlan<TError>(mutationOptions, client),
    getResolvePlanMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ResolvePlanResult, TError, ResolvePlanOptions>, "mutationFn">
    ) => getResolvePlanMutationOptions<TError>(mutationOptions, client),
    useResolvePlan: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<ResolvePlanResult, TError, ResolvePlanOptions>, "mutationFn">
    ) => useResolvePlan<TError>(mutationOptions, client),
    getRenderMarkdownMutationOptions: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RenderMarkdownResult, TError, RenderMarkdownOptions>, "mutationFn">
    ) => getRenderMarkdownMutationOptions<TError>(mutationOptions, client),
    useRenderMarkdown: <TError = unknown>(
      mutationOptions?: Omit<UseMutationOptions<RenderMarkdownResult, TError, RenderMarkdownOptions>, "mutationFn">
    ) => useRenderMarkdown<TError>(mutationOptions, client),
  };
}
