// Generated by wiz from omega.
// React Query options getters and hooks for query operations. Edit the document, not this file.

import { useQuery, type UseQueryOptions } from "@tanstack/react-query";
import { defaultClient, type Client, type GetFileContentOptions, type GetFileContentResult, type GetGitStatusOptions, type GetGitStatusResult, type GetPlanOptions, type GetPlanResult, type GetStateOptions, type GetStateResult, type GetTranscriptOptions, type GetTranscriptResult, type ListBranchPointsOptions, type ListBranchPointsResult, type ListCommandsOptions, type ListCommandsResult, type ListFilesOptions, type ListFilesResult, type ListModelsOptions, type ListModelsResult, type ListQueueOptions, type ListQueueResult, type ListWorkspacesOptions, type ListWorkspacesResult } from "./api.ts";
import { createMutations } from "./mutations.ts";

/**
 * List workspaces and their sessions
 * 
 * Every directory with sessions on disk, each with its sessions nested.
 */
export function getListWorkspacesQueryOptions<
  TData = ListWorkspacesResult,
  TError = unknown
>(
  options?: ListWorkspacesOptions,
  queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/workspaces", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listWorkspaces({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listWorkspaces`. */
export function useListWorkspaces<
  TData = ListWorkspacesResult,
  TError = unknown
>(
  options?: ListWorkspacesOptions,
  queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListWorkspacesQueryOptions(options!, queryOptions, client));
}

/**
 * List available models
 * 
 * Models the local omp install is authenticated for.
 */
export function getListModelsQueryOptions<
  TData = ListModelsResult,
  TError = unknown
>(
  options?: ListModelsOptions,
  queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/models", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listModels({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listModels`. */
export function useListModels<
  TData = ListModelsResult,
  TError = unknown
>(
  options?: ListModelsOptions,
  queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListModelsQueryOptions(options!, queryOptions, client));
}

/** Files in a workspace directory, relative to `cwd`. */
export function getListFilesQueryOptions<
  TData = ListFilesResult,
  TError = unknown
>(
  options?: ListFilesOptions,
  queryOptions?: Omit<UseQueryOptions<ListFilesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/files", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listFiles(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listFiles`. */
export function useListFiles<
  TData = ListFilesResult,
  TError = unknown
>(
  options?: ListFilesOptions,
  queryOptions?: Omit<UseQueryOptions<ListFilesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListFilesQueryOptions(options!, queryOptions, client));
}

/** Read content and metadata of a workspace file. */
export function getGetFileContentQueryOptions<
  TData = GetFileContentResult,
  TError = unknown
>(
  options: GetFileContentOptions,
  queryOptions?: Omit<UseQueryOptions<GetFileContentResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/files/content", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getFileContent(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getFileContent`. */
export function useGetFileContent<
  TData = GetFileContentResult,
  TError = unknown
>(
  options: GetFileContentOptions,
  queryOptions?: Omit<UseQueryOptions<GetFileContentResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetFileContentQueryOptions(options, queryOptions, client));
}

/** Git status for a workspace directory. */
export function getGetGitStatusQueryOptions<
  TData = GetGitStatusResult,
  TError = unknown
>(
  options?: GetGitStatusOptions,
  queryOptions?: Omit<UseQueryOptions<GetGitStatusResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/git/status", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getGitStatus(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getGitStatus`. */
export function useGetGitStatus<
  TData = GetGitStatusResult,
  TError = unknown
>(
  options?: GetGitStatusOptions,
  queryOptions?: Omit<UseQueryOptions<GetGitStatusResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetGitStatusQueryOptions(options!, queryOptions, client));
}

/**
 * Read live session state
 * 
 * Current model, thinking level, streaming status and plan state.
 */
export function getGetStateQueryOptions<
  TData = GetStateResult,
  TError = unknown
>(
  options: GetStateOptions,
  queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/state", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getState(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getState`. */
export function useGetState<
  TData = GetStateResult,
  TError = unknown
>(
  options: GetStateOptions,
  queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetStateQueryOptions(options, queryOptions, client));
}

/**
 * Read the session transcript
 * 
 * One page of the session transcript, flattened into renderable parts.
 * 
 * The newest `limit` messages by default; `before` walks backwards through
 * older history. Thinking and tool parts are dropped server-side when the
 * client says it will not draw them.
 */
export function getGetTranscriptQueryOptions<
  TData = GetTranscriptResult,
  TError = unknown
>(
  options: GetTranscriptOptions,
  queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/transcript", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getTranscript(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getTranscript`. */
export function useGetTranscript<
  TData = GetTranscriptResult,
  TError = unknown
>(
  options: GetTranscriptOptions,
  queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetTranscriptQueryOptions(options, queryOptions, client));
}

/**
 * List queued messages
 * 
 * The user messages waiting to be delivered, steering lane first.
 * 
 * Empty whenever the session is idle: a queue only exists while a turn is
 * in flight to queue behind.
 */
export function getListQueueQueryOptions<
  TData = ListQueueResult,
  TError = unknown
>(
  options: ListQueueOptions,
  queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/queue", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listQueue(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listQueue`. */
export function useListQueue<
  TData = ListQueueResult,
  TError = unknown
>(
  options: ListQueueOptions,
  queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListQueueQueryOptions(options, queryOptions, client));
}

/**
 * List MCP slash commands
 * 
 * Slash commands MCP servers contribute to this session.
 * 
 * Session-scoped rather than global: which servers are connected, and so
 * which prompts exist, is a property of the agent, not of the install.
 */
export function getListCommandsQueryOptions<
  TData = ListCommandsResult,
  TError = unknown
>(
  options: ListCommandsOptions,
  queryOptions?: Omit<UseQueryOptions<ListCommandsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/commands", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listCommands(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listCommands`. */
export function useListCommands<
  TData = ListCommandsResult,
  TError = unknown
>(
  options: ListCommandsOptions,
  queryOptions?: Omit<UseQueryOptions<ListCommandsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListCommandsQueryOptions(options, queryOptions, client));
}

/**
 * List branch points
 * 
 * The user messages this session can branch from, oldest first.
 */
export function getListBranchPointsQueryOptions<
  TData = ListBranchPointsResult,
  TError = unknown
>(
  options: ListBranchPointsOptions,
  queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/branch-points", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listBranchPoints(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listBranchPoints`. */
export function useListBranchPoints<
  TData = ListBranchPointsResult,
  TError = unknown
>(
  options: ListBranchPointsOptions,
  queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListBranchPointsQueryOptions(options, queryOptions, client));
}

/**
 * Read the plan document
 * 
 * The plan document, its headings and the executable role tiers — the three
 * planning panes in one payload.
 */
export function getGetPlanQueryOptions<
  TData = GetPlanResult,
  TError = unknown
>(
  options: GetPlanOptions,
  queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/plan", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getPlan(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getPlan`. */
export function useGetPlan<
  TData = GetPlanResult,
  TError = unknown
>(
  options: GetPlanOptions,
  queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetPlanQueryOptions(options, queryOptions, client));
}

/** Factory binding all query options getters and query hooks to a custom client instance. */
export function createQueries(client: Client = defaultClient()) {
  return {
    getListWorkspacesQueryOptions: <TData = ListWorkspacesResult, TError = unknown>(
      options?: ListWorkspacesOptions,
      queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListWorkspacesQueryOptions<TData, TError>(options!, queryOptions, client),
    useListWorkspaces: <TData = ListWorkspacesResult, TError = unknown>(
      options?: ListWorkspacesOptions,
      queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListWorkspaces<TData, TError>(options!, queryOptions, client),
    getListModelsQueryOptions: <TData = ListModelsResult, TError = unknown>(
      options?: ListModelsOptions,
      queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListModelsQueryOptions<TData, TError>(options!, queryOptions, client),
    useListModels: <TData = ListModelsResult, TError = unknown>(
      options?: ListModelsOptions,
      queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListModels<TData, TError>(options!, queryOptions, client),
    getListFilesQueryOptions: <TData = ListFilesResult, TError = unknown>(
      options?: ListFilesOptions,
      queryOptions?: Omit<UseQueryOptions<ListFilesResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListFilesQueryOptions<TData, TError>(options!, queryOptions, client),
    useListFiles: <TData = ListFilesResult, TError = unknown>(
      options?: ListFilesOptions,
      queryOptions?: Omit<UseQueryOptions<ListFilesResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListFiles<TData, TError>(options!, queryOptions, client),
    getGetFileContentQueryOptions: <TData = GetFileContentResult, TError = unknown>(
      options: GetFileContentOptions,
      queryOptions?: Omit<UseQueryOptions<GetFileContentResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetFileContentQueryOptions<TData, TError>(options, queryOptions, client),
    useGetFileContent: <TData = GetFileContentResult, TError = unknown>(
      options: GetFileContentOptions,
      queryOptions?: Omit<UseQueryOptions<GetFileContentResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetFileContent<TData, TError>(options, queryOptions, client),
    getGetGitStatusQueryOptions: <TData = GetGitStatusResult, TError = unknown>(
      options?: GetGitStatusOptions,
      queryOptions?: Omit<UseQueryOptions<GetGitStatusResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetGitStatusQueryOptions<TData, TError>(options!, queryOptions, client),
    useGetGitStatus: <TData = GetGitStatusResult, TError = unknown>(
      options?: GetGitStatusOptions,
      queryOptions?: Omit<UseQueryOptions<GetGitStatusResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetGitStatus<TData, TError>(options!, queryOptions, client),
    getGetStateQueryOptions: <TData = GetStateResult, TError = unknown>(
      options: GetStateOptions,
      queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetStateQueryOptions<TData, TError>(options, queryOptions, client),
    useGetState: <TData = GetStateResult, TError = unknown>(
      options: GetStateOptions,
      queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetState<TData, TError>(options, queryOptions, client),
    getGetTranscriptQueryOptions: <TData = GetTranscriptResult, TError = unknown>(
      options: GetTranscriptOptions,
      queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetTranscriptQueryOptions<TData, TError>(options, queryOptions, client),
    useGetTranscript: <TData = GetTranscriptResult, TError = unknown>(
      options: GetTranscriptOptions,
      queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetTranscript<TData, TError>(options, queryOptions, client),
    getListQueueQueryOptions: <TData = ListQueueResult, TError = unknown>(
      options: ListQueueOptions,
      queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListQueueQueryOptions<TData, TError>(options, queryOptions, client),
    useListQueue: <TData = ListQueueResult, TError = unknown>(
      options: ListQueueOptions,
      queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListQueue<TData, TError>(options, queryOptions, client),
    getListCommandsQueryOptions: <TData = ListCommandsResult, TError = unknown>(
      options: ListCommandsOptions,
      queryOptions?: Omit<UseQueryOptions<ListCommandsResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListCommandsQueryOptions<TData, TError>(options, queryOptions, client),
    useListCommands: <TData = ListCommandsResult, TError = unknown>(
      options: ListCommandsOptions,
      queryOptions?: Omit<UseQueryOptions<ListCommandsResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListCommands<TData, TError>(options, queryOptions, client),
    getListBranchPointsQueryOptions: <TData = ListBranchPointsResult, TError = unknown>(
      options: ListBranchPointsOptions,
      queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListBranchPointsQueryOptions<TData, TError>(options, queryOptions, client),
    useListBranchPoints: <TData = ListBranchPointsResult, TError = unknown>(
      options: ListBranchPointsOptions,
      queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListBranchPoints<TData, TError>(options, queryOptions, client),
    getGetPlanQueryOptions: <TData = GetPlanResult, TError = unknown>(
      options: GetPlanOptions,
      queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetPlanQueryOptions<TData, TError>(options, queryOptions, client),
    useGetPlan: <TData = GetPlanResult, TError = unknown>(
      options: GetPlanOptions,
      queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetPlan<TData, TError>(options, queryOptions, client),
  };
}

/** Factory binding all query and mutation hooks to a custom client instance. */
export function createHooks(client: Client = defaultClient()) {
  return {
    ...createQueries(client),
    ...createMutations(client),
  };
}
