// Generated by wiz from omega.
// React Query options getters and hooks for query operations. Edit the document, not this file.

import { useQuery, type UseQueryOptions } from "@tanstack/react-query";
import { defaultClient, type Client } from "./api.ts";
import { createMutations } from "./mutations.ts";

/**
 * List workspaces and their sessions
 * 
 * Every directory with sessions on disk, each with its sessions nested.
 */
export function getListWorkspacesQueryOptions<
  TData = Awaited<ReturnType<Client["listWorkspaces"]>>,
  TError = unknown
>(
  options?: Parameters<Client["listWorkspaces"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listWorkspaces"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/workspaces", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listWorkspaces({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listWorkspaces`. */
export function useListWorkspaces<
  TData = Awaited<ReturnType<Client["listWorkspaces"]>>,
  TError = unknown
>(
  options?: Parameters<Client["listWorkspaces"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listWorkspaces"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListWorkspacesQueryOptions(options!, queryOptions, client));
}

/**
 * List available models
 * 
 * Models the local omp install is authenticated for.
 */
export function getListModelsQueryOptions<
  TData = Awaited<ReturnType<Client["listModels"]>>,
  TError = unknown
>(
  options?: Parameters<Client["listModels"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listModels"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/models", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listModels({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listModels`. */
export function useListModels<
  TData = Awaited<ReturnType<Client["listModels"]>>,
  TError = unknown
>(
  options?: Parameters<Client["listModels"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listModels"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListModelsQueryOptions(options!, queryOptions, client));
}

/**
 * Read live session state
 * 
 * Current model, thinking level, streaming status and plan state.
 */
export function getGetStateQueryOptions<
  TData = Awaited<ReturnType<Client["getState"]>>,
  TError = unknown
>(
  options: Parameters<Client["getState"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getState"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/state", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getState(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getState`. */
export function useGetState<
  TData = Awaited<ReturnType<Client["getState"]>>,
  TError = unknown
>(
  options: Parameters<Client["getState"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getState"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetStateQueryOptions(options, queryOptions, client));
}

/**
 * Read the session transcript
 * 
 * The session transcript, flattened into renderable parts.
 */
export function getGetTranscriptQueryOptions<
  TData = Awaited<ReturnType<Client["getTranscript"]>>,
  TError = unknown
>(
  options: Parameters<Client["getTranscript"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getTranscript"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/transcript", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getTranscript(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getTranscript`. */
export function useGetTranscript<
  TData = Awaited<ReturnType<Client["getTranscript"]>>,
  TError = unknown
>(
  options: Parameters<Client["getTranscript"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getTranscript"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetTranscriptQueryOptions(options, queryOptions, client));
}

/**
 * Read the plan document
 * 
 * The plan document, its headings and the executable role tiers — the three
 * planning panes in one payload.
 */
export function getGetPlanQueryOptions<
  TData = Awaited<ReturnType<Client["getPlan"]>>,
  TError = unknown
>(
  options: Parameters<Client["getPlan"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getPlan"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/plan", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getPlan(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getPlan`. */
export function useGetPlan<
  TData = Awaited<ReturnType<Client["getPlan"]>>,
  TError = unknown
>(
  options: Parameters<Client["getPlan"]>[0],
  queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getPlan"]>>, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetPlanQueryOptions(options, queryOptions, client));
}

/** Factory binding all query options getters and query hooks to a custom client instance. */
export function createQueries(client: Client = defaultClient()) {
  return {
    getListWorkspacesQueryOptions: <TData = Awaited<ReturnType<Client["listWorkspaces"]>>, TError = unknown>(
      options?: Parameters<Client["listWorkspaces"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listWorkspaces"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => getListWorkspacesQueryOptions<TData, TError>(options!, queryOptions, client),
    useListWorkspaces: <TData = Awaited<ReturnType<Client["listWorkspaces"]>>, TError = unknown>(
      options?: Parameters<Client["listWorkspaces"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listWorkspaces"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => useListWorkspaces<TData, TError>(options!, queryOptions, client),
    getListModelsQueryOptions: <TData = Awaited<ReturnType<Client["listModels"]>>, TError = unknown>(
      options?: Parameters<Client["listModels"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listModels"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => getListModelsQueryOptions<TData, TError>(options!, queryOptions, client),
    useListModels: <TData = Awaited<ReturnType<Client["listModels"]>>, TError = unknown>(
      options?: Parameters<Client["listModels"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["listModels"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => useListModels<TData, TError>(options!, queryOptions, client),
    getGetStateQueryOptions: <TData = Awaited<ReturnType<Client["getState"]>>, TError = unknown>(
      options: Parameters<Client["getState"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getState"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => getGetStateQueryOptions<TData, TError>(options, queryOptions, client),
    useGetState: <TData = Awaited<ReturnType<Client["getState"]>>, TError = unknown>(
      options: Parameters<Client["getState"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getState"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => useGetState<TData, TError>(options, queryOptions, client),
    getGetTranscriptQueryOptions: <TData = Awaited<ReturnType<Client["getTranscript"]>>, TError = unknown>(
      options: Parameters<Client["getTranscript"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getTranscript"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => getGetTranscriptQueryOptions<TData, TError>(options, queryOptions, client),
    useGetTranscript: <TData = Awaited<ReturnType<Client["getTranscript"]>>, TError = unknown>(
      options: Parameters<Client["getTranscript"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getTranscript"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => useGetTranscript<TData, TError>(options, queryOptions, client),
    getGetPlanQueryOptions: <TData = Awaited<ReturnType<Client["getPlan"]>>, TError = unknown>(
      options: Parameters<Client["getPlan"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getPlan"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => getGetPlanQueryOptions<TData, TError>(options, queryOptions, client),
    useGetPlan: <TData = Awaited<ReturnType<Client["getPlan"]>>, TError = unknown>(
      options: Parameters<Client["getPlan"]>[0],
      queryOptions?: Omit<UseQueryOptions<Awaited<ReturnType<Client["getPlan"]>>, TError, TData>, "queryKey" | "queryFn">
    ) => useGetPlan<TData, TError>(options, queryOptions, client),
  };
}

/** Factory binding all query and mutation hooks to a custom client instance. */
export function createHooks(client: Client = defaultClient()) {
  return {
    ...createQueries(client),
    ...createMutations(client),
  };
}
