// Generated by wiz from omega.
// React Query options getters and hooks for query operations. Edit the document, not this file.

import { useQuery, type UseQueryOptions } from "@tanstack/react-query";
import { defaultClient, type Client, type GetPlanOptions, type GetPlanResult, type GetStateOptions, type GetStateResult, type GetTranscriptOptions, type GetTranscriptResult, type ListBranchPointsOptions, type ListBranchPointsResult, type ListModelsOptions, type ListModelsResult, type ListQueueOptions, type ListQueueResult, type ListWorkspacesOptions, type ListWorkspacesResult } from "./api.ts";
import { createMutations } from "./mutations.ts";

/**
 * List workspaces and their sessions
 * 
 * Every directory with sessions on disk, each with its sessions nested.
 */
export function getListWorkspacesQueryOptions<
  TData = ListWorkspacesResult,
  TError = unknown
>(
  options?: ListWorkspacesOptions,
  queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/workspaces", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listWorkspaces({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listWorkspaces`. */
export function useListWorkspaces<
  TData = ListWorkspacesResult,
  TError = unknown
>(
  options?: ListWorkspacesOptions,
  queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListWorkspacesQueryOptions(options!, queryOptions, client));
}

/**
 * List available models
 * 
 * Models the local omp install is authenticated for.
 */
export function getListModelsQueryOptions<
  TData = ListModelsResult,
  TError = unknown
>(
  options?: ListModelsOptions,
  queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/models", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listModels({ ...options, signal } as any),
    ...queryOptions,
  };
}

/** React Query hook for `listModels`. */
export function useListModels<
  TData = ListModelsResult,
  TError = unknown
>(
  options?: ListModelsOptions,
  queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListModelsQueryOptions(options!, queryOptions, client));
}

/**
 * Read live session state
 * 
 * Current model, thinking level, streaming status and plan state.
 */
export function getGetStateQueryOptions<
  TData = GetStateResult,
  TError = unknown
>(
  options: GetStateOptions,
  queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/state", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getState(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getState`. */
export function useGetState<
  TData = GetStateResult,
  TError = unknown
>(
  options: GetStateOptions,
  queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetStateQueryOptions(options, queryOptions, client));
}

/**
 * Read the session transcript
 * 
 * The session transcript, flattened into renderable parts.
 */
export function getGetTranscriptQueryOptions<
  TData = GetTranscriptResult,
  TError = unknown
>(
  options: GetTranscriptOptions,
  queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/transcript", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getTranscript(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getTranscript`. */
export function useGetTranscript<
  TData = GetTranscriptResult,
  TError = unknown
>(
  options: GetTranscriptOptions,
  queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetTranscriptQueryOptions(options, queryOptions, client));
}

/**
 * List queued messages
 * 
 * The user messages waiting to be delivered, steering lane first.
 * 
 * Empty whenever the session is idle: a queue only exists while a turn is
 * in flight to queue behind.
 */
export function getListQueueQueryOptions<
  TData = ListQueueResult,
  TError = unknown
>(
  options: ListQueueOptions,
  queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/queue", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listQueue(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listQueue`. */
export function useListQueue<
  TData = ListQueueResult,
  TError = unknown
>(
  options: ListQueueOptions,
  queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListQueueQueryOptions(options, queryOptions, client));
}

/**
 * List branch points
 * 
 * The user messages this session can branch from, oldest first.
 */
export function getListBranchPointsQueryOptions<
  TData = ListBranchPointsResult,
  TError = unknown
>(
  options: ListBranchPointsOptions,
  queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/branch-points", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.listBranchPoints(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `listBranchPoints`. */
export function useListBranchPoints<
  TData = ListBranchPointsResult,
  TError = unknown
>(
  options: ListBranchPointsOptions,
  queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getListBranchPointsQueryOptions(options, queryOptions, client));
}

/**
 * Read the plan document
 * 
 * The plan document, its headings and the executable role tiers — the three
 * planning panes in one payload.
 */
export function getGetPlanQueryOptions<
  TData = GetPlanResult,
  TError = unknown
>(
  options: GetPlanOptions,
  queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return {
    queryKey: ["/api/sessions/{key}/plan", options] as const,
    queryFn: ({ signal }: { signal?: AbortSignal }) =>
      client.getPlan(options as any, { signal }),
    ...queryOptions,
  };
}

/** React Query hook for `getPlan`. */
export function useGetPlan<
  TData = GetPlanResult,
  TError = unknown
>(
  options: GetPlanOptions,
  queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">,
  client: Client = defaultClient()
) {
  return useQuery(getGetPlanQueryOptions(options, queryOptions, client));
}

/** Factory binding all query options getters and query hooks to a custom client instance. */
export function createQueries(client: Client = defaultClient()) {
  return {
    getListWorkspacesQueryOptions: <TData = ListWorkspacesResult, TError = unknown>(
      options?: ListWorkspacesOptions,
      queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListWorkspacesQueryOptions<TData, TError>(options!, queryOptions, client),
    useListWorkspaces: <TData = ListWorkspacesResult, TError = unknown>(
      options?: ListWorkspacesOptions,
      queryOptions?: Omit<UseQueryOptions<ListWorkspacesResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListWorkspaces<TData, TError>(options!, queryOptions, client),
    getListModelsQueryOptions: <TData = ListModelsResult, TError = unknown>(
      options?: ListModelsOptions,
      queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListModelsQueryOptions<TData, TError>(options!, queryOptions, client),
    useListModels: <TData = ListModelsResult, TError = unknown>(
      options?: ListModelsOptions,
      queryOptions?: Omit<UseQueryOptions<ListModelsResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListModels<TData, TError>(options!, queryOptions, client),
    getGetStateQueryOptions: <TData = GetStateResult, TError = unknown>(
      options: GetStateOptions,
      queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetStateQueryOptions<TData, TError>(options, queryOptions, client),
    useGetState: <TData = GetStateResult, TError = unknown>(
      options: GetStateOptions,
      queryOptions?: Omit<UseQueryOptions<GetStateResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetState<TData, TError>(options, queryOptions, client),
    getGetTranscriptQueryOptions: <TData = GetTranscriptResult, TError = unknown>(
      options: GetTranscriptOptions,
      queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetTranscriptQueryOptions<TData, TError>(options, queryOptions, client),
    useGetTranscript: <TData = GetTranscriptResult, TError = unknown>(
      options: GetTranscriptOptions,
      queryOptions?: Omit<UseQueryOptions<GetTranscriptResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetTranscript<TData, TError>(options, queryOptions, client),
    getListQueueQueryOptions: <TData = ListQueueResult, TError = unknown>(
      options: ListQueueOptions,
      queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListQueueQueryOptions<TData, TError>(options, queryOptions, client),
    useListQueue: <TData = ListQueueResult, TError = unknown>(
      options: ListQueueOptions,
      queryOptions?: Omit<UseQueryOptions<ListQueueResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListQueue<TData, TError>(options, queryOptions, client),
    getListBranchPointsQueryOptions: <TData = ListBranchPointsResult, TError = unknown>(
      options: ListBranchPointsOptions,
      queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">
    ) => getListBranchPointsQueryOptions<TData, TError>(options, queryOptions, client),
    useListBranchPoints: <TData = ListBranchPointsResult, TError = unknown>(
      options: ListBranchPointsOptions,
      queryOptions?: Omit<UseQueryOptions<ListBranchPointsResult, TError, TData>, "queryKey" | "queryFn">
    ) => useListBranchPoints<TData, TError>(options, queryOptions, client),
    getGetPlanQueryOptions: <TData = GetPlanResult, TError = unknown>(
      options: GetPlanOptions,
      queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">
    ) => getGetPlanQueryOptions<TData, TError>(options, queryOptions, client),
    useGetPlan: <TData = GetPlanResult, TError = unknown>(
      options: GetPlanOptions,
      queryOptions?: Omit<UseQueryOptions<GetPlanResult, TError, TData>, "queryKey" | "queryFn">
    ) => useGetPlan<TData, TError>(options, queryOptions, client),
  };
}

/** Factory binding all query and mutation hooks to a custom client instance. */
export function createHooks(client: Client = defaultClient()) {
  return {
    ...createQueries(client),
    ...createMutations(client),
  };
}
